627181	<?xml version="1.0" encoding="utf-8" ?>    <insert_update_zap_reg xmlns="urn:gmi:nova:leasing">    <is_update>true</is_update>    <id_zapo>R057888</id_zapo>    <id_cont>71627</id_cont>        <vrsta>OV</vrsta>    <znamka>RENAULT</znamka>        <tip>CAPTUR INTENS BLUE DCI 95</tip>    <st_sas>VF1RJB00866444389</st_sas>    <st_mot></st_mot>        <let_pro>2020</let_pro>    <barva>BIJELA&CRNA</barva>    <reg_stev>VŽ411IJ</reg_stev>    <st_promd>14753372</st_promd>    <dat_pd>2021-02-09T00:00:00</dat_pd>    <velj_pd>2023-02-09T00:00:00</velj_pd>    <opis>RENAULT CAPTUR INTENS BLUE DCI 95</opis>    <spl_pog></spl_pog>    <id_kupca>022720</id_kupca>    <id_dob>022720</id_dob>    <ps_kw>70</ps_kw>    <kubik>1461</kubik>    <vnesel></vnesel>    <st_kljuc></st_kljuc>    <identicar></identicar>        <komentar></komentar>    <st_sedezev>0</st_sedezev>    <nosilnost></nosilnost>    <mesto_upo></mesto_upo>    <st_knj_vozila>       </st_knj_vozila>    <stopnja_am>0.00</stopnja_am>    <st_fakture></st_fakture>        <ali_v_os>false</ali_v_os>    <nabav_vred>0.00</nabav_vred>    <prenos></prenos>    <teza_praz></teza_praz>        <sys_ts>501338566</sys_ts>    <kilometri>0</kilometri>    <dat_1upor>2021-02-09T00:00:00</dat_1upor>    <rabljeno>false</rabljeno>    <prodano>true</prodano>    <co2_emission>106.0000</co2_emission><co2_unit>g/km</co2_unit><update_dokument>      <sifra_PROM>false</sifra_PROM>      <sifra_KVOZ>false</sifra_KVOZ>      <reg_stev>false</reg_stev>    </update_dokument>    <comment>Označavanje zapisnika prodanim automatskom obradom (event)</comment>    <id_rep_category>999</id_rep_category>    <updated_values>      <table_name>ZAP_REG</table_name>      <name>PRODANO</name>      <updated_value>true</updated_value>    </updated_values>    </insert_update_zap_reg>	2024-02-05 14:38:42.303	0	0	NULL	NULL	NULL	E	2024-02-05 15:55:57.857	2024-02-05 15:55:57.873	NULL	System.Xml.XmlException: An error occurred while parsing EntityName. Line 15, position 17.     at System.Xml.XmlTextReaderImpl.Throw(Exception e)     at System.Xml.XmlTextReaderImpl.ParseEntityName()     at System.Xml.XmlTextReaderImpl.ParseEntityReference()     at System.Xml.XmlTextReaderImpl.Read()     at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)     at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)     at System.Xml.XmlDocument.Load(XmlReader reader)     at System.Xml.XmlDocument.LoadXml(String xml)     at GMI.Core.GMI_ProcessXmlEngine.Handle(GMI_Session session, String xml, Boolean is_async)     at GMI.Core.Queue.ProcessPendingRequest(QueueRequest2 req)	D20F24D5-75DC-4DE1-B808-2421C10E177F	NULL	NULL	2024-02-05 14:39:42.310	ivap1     	RLENOVAAPP-P	NULL	1800000	NULL	NULL
627182	<?xml version="1.0" encoding="utf-8" ?>    <insert_update_zap_reg xmlns="urn:gmi:nova:leasing">    <is_update>true</is_update>    <id_zapo>R072226</id_zapo>    <id_cont>84581</id_cont>        <vrsta>OV</vrsta>    <znamka>RENAULT</znamka>        <tip>CAPTUR INTENS BLUE DCI 95</tip>    <st_sas>VF1RJB00866444389</st_sas>    <st_mot></st_mot>        <let_pro>2020</let_pro>    <barva>BIJELA&CRNA</barva>    <reg_stev>VŽ411IJ</reg_stev>    <st_promd>14753372</st_promd>    <dat_pd>2021-02-09T00:00:00</dat_pd>    <velj_pd>2023-02-09T00:00:00</velj_pd>    <opis>RENAULT CAPTUR INTENS BLUE DCI 95</opis>    <spl_pog></spl_pog>    <id_kupca>013767</id_kupca>    <id_dob>022720</id_dob>    <ps_kw>70</ps_kw>    <kubik>1461</kubik>    <vnesel></vnesel>    <st_kljuc></st_kljuc>    <identicar></identicar>        <komentar></komentar>    <st_sedezev>0</st_sedezev>    <nosilnost></nosilnost>    <mesto_upo></mesto_upo>    <st_knj_vozila>       </st_knj_vozila>    <stopnja_am>0.00</stopnja_am>    <st_fakture></st_fakture>        <ali_v_os>false</ali_v_os>    <nabav_vred>0.00</nabav_vred>    <prenos></prenos>    <teza_praz></teza_praz>        <sys_ts>519942032</sys_ts>    <kilometri>0</kilometri>    <dat_1upor>2021-02-09T00:00:00</dat_1upor>    <rabljeno>false</rabljeno>    <prodano>true</prodano>    <co2_emission>106.0000</co2_emission><co2_unit>g/km</co2_unit><update_dokument>      <sifra_PROM>false</sifra_PROM>      <sifra_KVOZ>false</sifra_KVOZ>      <reg_stev>false</reg_stev>    </update_dokument>    <comment>Označavanje zapisnika prodanim automatskom obradom (event)</comment>    <id_rep_category>999</id_rep_category>    <updated_values>      <table_name>ZAP_REG</table_name>      <name>PRODANO</name>      <updated_value>true</updated_value>    </updated_values>    </insert_update_zap_reg>	2024-02-05 14:38:42.320	0	0	NULL	NULL	NULL	E	2024-02-05 15:55:57.873	2024-02-05 15:55:57.903	NULL	System.Xml.XmlException: An error occurred while parsing EntityName. Line 15, position 17.     at System.Xml.XmlTextReaderImpl.Throw(Exception e)     at System.Xml.XmlTextReaderImpl.ParseEntityName()     at System.Xml.XmlTextReaderImpl.ParseEntityReference()     at System.Xml.XmlTextReaderImpl.Read()     at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)     at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)     at System.Xml.XmlDocument.Load(XmlReader reader)     at System.Xml.XmlDocument.LoadXml(String xml)     at GMI.Core.GMI_ProcessXmlEngine.Handle(GMI_Session session, String xml, Boolean is_async)     at GMI.Core.Queue.ProcessPendingRequest(QueueRequest2 req)	D20F24D5-75DC-4DE1-B808-2421C10E177F	NULL	NULL	2024-02-05 14:39:42.310	ivap1     	RLENOVAAPP-P	NULL	1800000	NULL	NULL





select PRODANO, * from dbo.zap_reg where id_zapo = 'R057888'
select PRODANO, dbo.gfn_Id_pog4Id_cont(id_cont) as Ugoovr, * from dbo.zap_reg where id_zapo ='R072226'

select* from dbo.queue_pending

select * from dbo.queue_pending where id in (627181, 627182)


delete from dbo.queue_pending where id in (627181, 627182)