begin tran
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0111','Growing of cereals (except rice), leguminous crops and oil seeds','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0112','Growing of rice','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0113','Growing of vegetables and melons, roots and tubers','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0114','Growing of sugar cane','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0115','Growing of tobacco','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0116','Growing of fibre crops','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0119','Growing of other non-perennial crops','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0121','Growing of grapes','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0122','Growing of tropical and subtropical fruits','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0123','Growing of citrus fruits','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0124','Growing of pome fruits and stone fruits','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0125','Growing of other tree and bush fruits and nuts','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0126','Growing of oleaginous fruits','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0127','Growing of beverage crops','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0128','Growing of spices, aromatic, drug and pharmaceutical crops','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0129','Growing of other perennial crops','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0130','Plant propagation','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0141','Raising of dairy cattle','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0142','Raising of other cattle and buffaloes','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0143','Raising of horses and other equines','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0144','Raising of camels and camelids','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0145','Raising of sheep and goats','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0146','Raising of swine/pigs','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0147','Raising of poultry','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0149','Raising of other animals','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0150','Mixed farming','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0161','Support activities for crop production','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0162','Support activities for animal production','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0163','Post-harvest crop activities','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0164','Seed processing for propagation','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0170','Hunting, trapping and related service activities','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0210','Silviculture and other forestry activities','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0220','Logging','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0230','Gathering of wild growing non-wood products','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0240','Support services to forestry','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0311','Marine fishing','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0312','Freshwater fishing','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0321','Marine aquaculture','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0322','Freshwater aquaculture','A')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0510','Mining of hard coal','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0520','Mining of lignite','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0610','Extraction of crude petroleum','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0620','Extraction of natural gas','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0710','Mining of iron ores','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0721','Mining of uranium and thorium ores','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0729','Mining of other non-ferrous metal ores','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0811','Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0812','Operation of gravel and sand pits; mining of clays and kaolin','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0891','Mining of chemical and fertiliser minerals','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0892','Extraction of peat','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0893','Extraction of salt','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0899','Other mining and quarrying n.e.c.','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0910','Support activities for petroleum and natural gas extraction','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0990','Support activities for other mining and quarrying','B')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1011','Processing and preserving of meat','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1012','Processing and preserving of poultry meat','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1013','Production of meat and poultry meat products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1020','Processing and preserving of fish, crustaceans and molluscs','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1031','Processing and preserving of potatoes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1032','Manufacture of fruit and vegetable juice','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1039','Other processing and preserving of fruit and vegetables','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1041','Manufacture of oils and fats','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1042','Manufacture of margarine and similar edible fats','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1051','Operation of dairies and cheese making','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1052','Manufacture of ice cream','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1061','Manufacture of grain mill products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1062','Manufacture of starches and starch products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1071','Manufacture of bread; manufacture of fresh pastry goods and cakes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1072','Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1073','Manufacture of macaroni, noodles, couscous and similar farinaceous products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1081','Manufacture of sugar','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1082','Manufacture of cocoa, chocolate and sugar confectionery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1083','Processing of tea and coffee','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1084','Manufacture of condiments and seasonings','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1085','Manufacture of prepared meals and dishes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1086','Manufacture of homogenised food preparations and dietetic food','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1089','Manufacture of other food products n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1091','Manufacture of prepared feeds for farm animals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1092','Manufacture of prepared pet foods','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1101','Distilling, rectifying and blending of spirits','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1102','Manufacture of wine from grape','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1103','Manufacture of cider and other fruit wines','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1104','Manufacture of other non-distilled fermented beverages','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1105','Manufacture of beer','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1106','Manufacture of malt','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1107','Manufacture of soft drinks; production of mineral waters and other bottled waters','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1200','Manufacture of tobacco products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1310','Preparation and spinning of textile fibres','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1320','Weaving of textiles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1330','Finishing of textiles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1391','Manufacture of knitted and crocheted fabrics','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1392','Manufacture of made-up textile articles, except apparel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1393','Manufacture of carpets and rugs','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1394','Manufacture of cordage, rope, twine and netting','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1395','Manufacture of non-wovens and articles made from non-wovens, except apparel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1396','Manufacture of other technical and industrial textiles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1399','Manufacture of other textiles n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1411','Manufacture of leather clothes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1412','Manufacture of workwear','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1413','Manufacture of other outerwear','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1414','Manufacture of underwear','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1419','Manufacture of other wearing apparel and accessories','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1420','Manufacture of articles of fur','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1431','Manufacture of knitted and crocheted hosiery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1439','Manufacture of other knitted and crocheted apparel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1511','Tanning and dressing of leather; dressing and dyeing of fur','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1512','Manufacture of luggage, handbags and the like, saddlery and harness','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1520','Manufacture of footwear','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1610','Sawmilling and planing of wood','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1621','Manufacture of veneer sheets and wood-based panels','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1622','Manufacture of assembled parquet floors','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1623','Manufacture of other builders carpentry and joinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1624','Manufacture of wooden containers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1629','Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1711','Manufacture of pulp','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1712','Manufacture of paper and paperboard','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1721','Manufacture of corrugated paper and paperboard and of containers of paper and paperboard','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1722','Manufacture of household and sanitary goods and of toilet requisites','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1723','Manufacture of paper stationery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1724','Manufacture of wallpaper','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1729','Manufacture of other articles of paper and paperboard','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1811','Printing of newspapers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1812','Other printing','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1813','Pre-press and pre-media services','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1814','Binding and related services','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1820','Reproduction of recorded media','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1910','Manufacture of coke oven products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','1920','Manufacture of refined petroleum products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2011','Manufacture of industrial gases','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2012','Manufacture of dyes and pigments','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2013','Manufacture of other inorganic basic chemicals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2014','Manufacture of other organic basic chemicals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2015','Manufacture of fertilisers and nitrogen compounds','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2016','Manufacture of plastics in primary forms','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2017','Manufacture of synthetic rubber in primary forms','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2020','Manufacture of pesticides and other agrochemical products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2030','Manufacture of paints, varnishes and similar coatings, printing ink and mastics','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2041','Manufacture of soap and detergents, cleaning and polishing preparations','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2042','Manufacture of perfumes and toilet preparations','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2051','Manufacture of explosives','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2052','Manufacture of glues','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2053','Manufacture of essential oils','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2059','Manufacture of other chemical products n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2060','Manufacture of man-made fibres','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2110','Manufacture of basic pharmaceutical products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2120','Manufacture of pharmaceutical preparations','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2211','Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2219','Manufacture of other rubber products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2221','Manufacture of plastic plates, sheets, tubes and profiles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2222','Manufacture of plastic packing goods','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2223','Manufacture of builders’ ware of plastic','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2229','Manufacture of other plastic products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2311','Manufacture of flat glass','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2312','Shaping and processing of flat glass','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2313','Manufacture of hollow glass','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2314','Manufacture of glass fibres','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2319','Manufacture and processing of other glass, including technical glassware','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2320','Manufacture of refractory products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2331','Manufacture of ceramic tiles and flags','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2332','Manufacture of bricks, tiles and construction products, in baked clay','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2341','Manufacture of ceramic household and ornamental articles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2342','Manufacture of ceramic sanitary fixtures','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2343','Manufacture of ceramic insulators and insulating fittings','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2344','Manufacture of other technical ceramic products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2349','Manufacture of other ceramic products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2351','Manufacture of cement','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2352','Manufacture of lime and plaster','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2361','Manufacture of concrete products for construction purposes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2362','Manufacture of plaster products for construction purposes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2363','Manufacture of ready-mixed concrete','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2364','Manufacture of mortars','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2365','Manufacture of fibre cement','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2369','Manufacture of other articles of concrete, plaster and cement','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2370','Cutting, shaping and finishing of stone','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2391','Production of abrasive products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2399','Manufacture of other non-metallic mineral products n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2410','Manufacture of basic iron and steel and of ferro-alloys','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2420','Manufacture of tubes, pipes, hollow profiles and related fittings, of steel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2431','Cold drawing of bars','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2432','Cold rolling of narrow strip','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2433','Cold forming or folding','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2434','Cold drawing of wire','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2441','Precious metals production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2442','Aluminium production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2443','Lead, zinc and tin production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2444','Copper production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2445','Other non-ferrous metal production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2446','Processing of nuclear fuel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2451','Casting of iron','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2452','Casting of steel','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2453','Casting of light metals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2454','Casting of other non-ferrous metals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2511','Manufacture of metal structures and parts of structures','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2512','Manufacture of doors and windows of metal','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2521','Manufacture of central heating radiators and boilers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2529','Manufacture of other tanks, reservoirs and containers of metal','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2530','Manufacture of steam generators, except central heating hot water boilers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2540','Manufacture of weapons and ammunition','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2550','Forging, pressing, stamping and roll-forming of metal; powder metallurgy','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2561','Treatment and coating of metals','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2562','Machining','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2571','Manufacture of cutlery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2572','Manufacture of locks and hinges','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2573','Manufacture of tools','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2591','Manufacture of steel drums and similar containers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2592','Manufacture of light metal packaging','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2593','Manufacture of wire products, chain and springs','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2594','Manufacture of fasteners and screw machine products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2599','Manufacture of other fabricated metal products n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2611','Manufacture of electronic components','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2612','Manufacture of loaded electronic boards','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2620','Manufacture of computers and peripheral equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2630','Manufacture of communication equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2640','Manufacture of consumer electronics','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2651','Manufacture of instruments and appliances for measuring, testing and navigation','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2652','Manufacture of watches and clocks','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2660','Manufacture of irradiation, electromedical and electrotherapeutic equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2670','Manufacture of optical instruments and photographic equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2680','Manufacture of magnetic and optical media','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2711','Manufacture of electric motors, generators and transformers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2712','Manufacture of electricity distribution and control apparatus','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2720','Manufacture of batteries and accumulators','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2731','Manufacture of fibre optic cables','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2732','Manufacture of other electronic and electric wires and cables','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2733','Manufacture of wiring devices','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2740','Manufacture of electric lighting equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2751','Manufacture of electric domestic appliances','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2752','Manufacture of non-electric domestic appliances','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2790','Manufacture of other electrical equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2811','Manufacture of engines and turbines, except aircraft, vehicle and cycle engines','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2812','Manufacture of fluid power equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2813','Manufacture of other pumps and compressors','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2814','Manufacture of other taps and valves','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2815','Manufacture of bearings, gears, gearing and driving elements','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2821','Manufacture of ovens, furnaces and furnace burners','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2822','Manufacture of lifting and handling equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2823','Manufacture of office machinery and equipment (except computers and peripheral equipment)','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2824','Manufacture of power-driven hand tools','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2825','Manufacture of non-domestic cooling and ventilation equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2829','Manufacture of other general-purpose machinery n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2830','Manufacture of agricultural and forestry machinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2841','Manufacture of metal forming machinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2849','Manufacture of other machine tools','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2891','Manufacture of machinery for metallurgy','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2892','Manufacture of machinery for mining, quarrying and construction','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2893','Manufacture of machinery for food, beverage and tobacco processing','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2894','Manufacture of machinery for textile, apparel and leather production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2895','Manufacture of machinery for paper and paperboard production','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2896','Manufacture of plastics and rubber machinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2899','Manufacture of other special-purpose machinery n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2910','Manufacture of motor vehicles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2920','Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2931','Manufacture of electrical and electronic equipment for motor vehicles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','2932','Manufacture of other parts and accessories for motor vehicles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3011','Building of ships and floating structures','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3012','Building of pleasure and sporting boats','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3020','Manufacture of railway locomotives and rolling stock','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3030','Manufacture of air and spacecraft and related machinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3040','Manufacture of military fighting vehicles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3091','Manufacture of motorcycles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3092','Manufacture of bicycles and invalid carriages','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3099','Manufacture of other transport equipment n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3101','Manufacture of office and shop furniture','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3102','Manufacture of kitchen furniture','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3103','Manufacture of mattresses','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3109','Manufacture of other furniture','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3211','Striking of coins','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3212','Manufacture of jewellery and related articles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3213','Manufacture of imitation jewellery and related articles','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3220','Manufacture of musical instruments','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3230','Manufacture of sports goods','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3240','Manufacture of games and toys','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3250','Manufacture of medical and dental instruments and supplies','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3291','Manufacture of brooms and brushes','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3299','Other manufacturing n.e.c.','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3311','Repair of fabricated metal products','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3312','Repair of machinery','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3313','Repair of electronic and optical equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3314','Repair of electrical equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3315','Repair and maintenance of ships and boats','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3316','Repair and maintenance of aircraft and spacecraft','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3317','Repair and maintenance of other transport equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3319','Repair of other equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3320','Installation of industrial machinery and equipment','C')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3511','Production of electricity','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3512','Transmission of electricity','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3513','Distribution of electricity','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3514','Trade of electricity','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3521','Manufacture of gas','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3522','Distribution of gaseous fuels through mains','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3523','Trade of gas through mains','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3530','Steam and air conditioning supply','D')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3600','Water collection, treatment and supply','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3700','Sewerage','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3811','Collection of non-hazardous waste','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3812','Collection of hazardous waste','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3821','Treatment and disposal of non-hazardous waste','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3822','Treatment and disposal of hazardous waste','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3831','Dismantling of wrecks','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3832','Recovery of sorted materials','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','3900','Remediation activities and other waste management services','E')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4110','Development of building projects','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4120','Construction of residential and non-residential buildings','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4211','Construction of roads and motorways','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4212','Construction of railways and underground railways','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4213','Construction of bridges and tunnels','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4221','Construction of utility projects for fluids','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4222','Construction of utility projects for electricity and telecommunications','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4291','Construction of water projects','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4299','Construction of other civil engineering projects n.e.c.','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4311','Demolition','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4312','Site preparation','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4313','Test drilling and boring','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4321','Electrical installation','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4322','Plumbing, heat and air-conditioning installation','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4329','Other construction installation','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4331','Plastering','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4332','Joinery installation','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4333','Floor and wall covering','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4334','Painting and glazing','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4339','Other building completion and finishing','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4391','Roofing activities','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4399','Other specialised construction activities n.e.c.','F')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4511','Sale of cars and light motor vehicles','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4519','Sale of other motor vehicles','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4520','Maintenance and repair of motor vehicles','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4531','Wholesale trade of motor vehicle parts and accessories','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4532','Retail trade of motor vehicle parts and accessories','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4540','Sale, maintenance and repair of motorcycles and related parts and accessories','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4611','Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4612','Agents involved in the sale of fuels, ores, metals and industrial chemicals','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4613','Agents involved in the sale of timber and building materials','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4614','Agents involved in the sale of machinery, industrial equipment, ships and aircraft','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4615','Agents involved in the sale of furniture, household goods, hardware and ironmongery','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4616','Agents involved in the sale of textiles, clothing, fur, footwear and leather goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4617','Agents involved in the sale of food, beverages and tobacco','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4618','Agents specialised in the sale of other particular products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4619','Agents involved in the sale of a variety of goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4621','Wholesale of grain, unmanufactured tobacco, seeds and animal feeds','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4622','Wholesale of flowers and plants','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4623','Wholesale of live animals','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4624','Wholesale of hides, skins and leather','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4631','Wholesale of fruit and vegetables','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4632','Wholesale of meat and meat products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4633','Wholesale of dairy products, eggs and edible oils and fats','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4634','Wholesale of beverages','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4635','Wholesale of tobacco products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4636','Wholesale of sugar and chocolate and sugar confectionery','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4637','Wholesale of coffee, tea, cocoa and spices','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4638','Wholesale of other food, including fish, crustaceans and molluscs','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4639','Non-specialised wholesale of food, beverages and tobacco','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4641','Wholesale of textiles','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4642','Wholesale of clothing and footwear','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4643','Wholesale of electrical household appliances','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4644','Wholesale of china and glassware and cleaning materials','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4645','Wholesale of perfume and cosmetics','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4646','Wholesale of pharmaceutical goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4647','Wholesale of furniture, carpets and lighting equipment','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4648','Wholesale of watches and jewellery','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4649','Wholesale of other household goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4651','Wholesale of computers, computer peripheral equipment and software','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4652','Wholesale of electronic and telecommunications equipment and parts','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4661','Wholesale of agricultural machinery, equipment and supplies','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4662','Wholesale of machine tools','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4663','Wholesale of mining, construction and civil engineering machinery','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4664','Wholesale of machinery for the textile industry and of sewing and knitting machines','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4665','Wholesale of office furniture','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4666','Wholesale of other office machinery and equipment','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4669','Wholesale of other machinery and equipment','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4671','Wholesale of solid, liquid and gaseous fuels and related products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4672','Wholesale of metals and metal ores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4673','Wholesale of wood, construction materials and sanitary equipment','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4674','Wholesale of hardware, plumbing and heating equipment and supplies','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4675','Wholesale of chemical products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4676','Wholesale of other intermediate products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4677','Wholesale of waste and scrap','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4690','Non-specialised wholesale trade','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4711','Retail sale in non-specialised stores with food, beverages or tobacco predominating','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4719','Other retail sale in non-specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4721','Retail sale of fruit and vegetables in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4722','Retail sale of meat and meat products in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4723','Retail sale of fish, crustaceans and molluscs in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4724','Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4725','Retail sale of beverages in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4726','Retail sale of tobacco products in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4729','Other retail sale of food in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4730','Retail sale of automotive fuel in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4741','Retail sale of computers, peripheral units and software in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4742','Retail sale of telecommunications equipment in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4743','Retail sale of audio and video equipment in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4751','Retail sale of textiles in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4752','Retail sale of hardware, paints and glass in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4753','Retail sale of carpets, rugs, wall and floor coverings in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4754','Retail sale of electrical household appliances in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4759','Retail sale of furniture, lighting equipment and other household articles in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4761','Retail sale of books in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4762','Retail sale of newspapers and stationery in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4763','Retail sale of music and video recordings in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4764','Retail sale of sporting equipment in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4765','Retail sale of games and toys in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4771','Retail sale of clothing in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4772','Retail sale of footwear and leather goods in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4773','Dispensing chemist in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4774','Retail sale of medical and orthopaedic goods in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4775','Retail sale of cosmetic and toilet articles in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4776','Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4777','Retail sale of watches and jewellery in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4778','Other retail sale of new goods in specialised stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4779','Retail sale of second-hand goods in stores','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4781','Retail sale via stalls and markets of food, beverages and tobacco products','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4782','Retail sale via stalls and markets of textiles, clothing and footwear','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4789','Retail sale via stalls and markets of other goods','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4791','Retail sale via mail order houses or via Internet','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4799','Other retail sale not in stores, stalls or markets','G')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4910','Passenger rail transport, interurban','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4920','Freight rail transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4931','Urban and suburban passenger land transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4932','Taxi operation','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4939','Other passenger land transport n.e.c.','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4941','Freight transport by road','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4942','Removal services','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','4950','Transport via pipeline','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5010','Sea and coastal passenger water transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5020','Sea and coastal freight water transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5030','Inland passenger water transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5040','Inland freight water transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5110','Passenger air transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5121','Freight air transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5122','Space transport','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5210','Warehousing and storage','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5221','Service activities incidental to land transportation','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5222','Service activities incidental to water transportation','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5223','Service activities incidental to air transportation','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5224','Cargo handling','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5229','Other transportation support activities','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5310','Postal activities under universal service obligation','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5320','Other postal and courier activities','H')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5510','Hotels and similar accommodation','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5520','Holiday and other short-stay accommodation','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5530','Camping grounds, recreational vehicle parks and trailer parks','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5590','Other accommodation','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5610','Restaurants and mobile food service activities','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5621','Event catering activities','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5629','Other food service activities','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5630','Beverage serving activities','I')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5811','Book publishing','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5812','Publishing of directories and mailing lists','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5813','Publishing of newspapers','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5814','Publishing of journals and periodicals','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5819','Other publishing activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5821','Publishing of computer games','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5829','Other software publishing','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5911','Motion picture, video and television programme production activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5912','Motion picture, video and television programme post-production activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5913','Motion picture, video and television programme distribution activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5914','Motion picture projection activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','5920','Sound recording and music publishing activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6010','Radio broadcasting','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6020','Television programming and broadcasting activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6110','Wired telecommunications activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6120','Wireless telecommunications activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6130','Satellite telecommunications activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6190','Other telecommunications activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6201','Computer programming activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6202','Computer consultancy activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6203','Computer facilities management activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6209','Other information technology and computer service activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6311','Data processing, hosting and related activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6312','Web portals','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6391','News agency activities','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6399','Other information service activities n.e.c.','J')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6411','Central banking','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6419','Other monetary intermediation','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6420','Activities of holding companies','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6430','Trusts, funds and similar financial entities','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6491','Financial leasing','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6492','Other credit granting','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6499','Other financial service activities, except insurance and pension funding n.e.c.','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6511','Life insurance','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6512','Non-life insurance','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6520','Reinsurance','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6530','Pension funding','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6611','Administration of financial markets','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6612','Security and commodity contracts brokerage','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6619','Other activities auxiliary to financial services, except insurance and pension funding','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6621','Risk and damage evaluation','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6622','Activities of insurance agents and brokers','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6629','Other activities auxiliary to insurance and pension funding','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6630','Fund management activities','K')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6810','Buying and selling of own real estate','L')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6820','Renting and operating of own or leased real estate','L')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6831','Real estate agencies','L')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6832','Management of real estate on a fee or contract basis','L')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6910','Legal activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','6920','Accounting, bookkeeping and auditing activities; tax consultancy','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7010','Activities of head offices','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7021','Public relations and communication activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7022','Business and other management consultancy activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7111','Architectural activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7112','Engineering activities and related technical consultancy','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7120','Technical testing and analysis','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7211','Research and experimental development on biotechnology','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7219','Other research and experimental development on natural sciences and engineering','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7220','Research and experimental development on social sciences and humanities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7311','Advertising agencies','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7312','Media representation','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7320','Market research and public opinion polling','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7410','Specialised design activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7420','Photographic activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7430','Translation and interpretation activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7490','Other professional, scientific and technical activities n.e.c.','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7500','Veterinary activities','M')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7711','Renting and leasing of cars and light motor vehicles','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7712','Renting and leasing of trucks','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7721','Renting and leasing of recreational and sports goods','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7722','Renting of video tapes and disks','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7729','Renting and leasing of other personal and household goods','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7731','Renting and leasing of agricultural machinery and equipment','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7732','Renting and leasing of construction and civil engineering machinery and equipment','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7733','Renting and leasing of office machinery and equipment (including computers)','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7734','Renting and leasing of water transport equipment','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7735','Renting and leasing of air transport equipment','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7739','Renting and leasing of other machinery, equipment and tangible goods n.e.c.','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7740','Leasing of intellectual property and similar products, except copyrighted works','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7810','Activities of employment placement agencies','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7820','Temporary employment agency activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7830','Other human resources provision','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7911','Travel agency activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7912','Tour operator activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','7990','Other reservation service and related activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8010','Private security activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8020','Security systems service activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8030','Investigation activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8110','Combined facilities support activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8121','General cleaning of buildings','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8122','Other building and industrial cleaning activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8129','Other cleaning activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8130','Landscape service activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8211','Combined office administrative service activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8219','Photocopying, document preparation and other specialised office support activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8220','Activities of call centres','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8230','Organisation of conventions and trade shows','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8291','Activities of collection agencies and credit bureaus','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8292','Packaging activities','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8299','Other business support service activities n.e.c.','N')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8411','General public administration activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8412','Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8413','Regulation of and contribution to more efficient operation of businesses','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8421','Foreign affairs','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8422','Defence activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8423','Justice and judicial activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8424','Public order and safety activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8425','Fire service activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8430','Compulsory social security activities','O')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8510','Pre-primary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8520','Primary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8531','General secondary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8532','Technical and vocational secondary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8541','Post-secondary non-tertiary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8542','Tertiary education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8551','Sports and recreation education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8552','Cultural education','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8553','Driving school activities','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8559','Other education n.e.c.','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8560','Educational support activities','P')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8610','Hospital activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8621','General medical practice activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8622','Specialist medical practice activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8623','Dental practice activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8690','Other human health activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8710','Residential nursing care activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8720','Residential care activities for mental retardation, mental health and substance abuse','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8730','Residential care activities for the elderly and disabled','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8790','Other residential care activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8810','Social work activities without accommodation for the elderly and disabled','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8891','Child day-care activities','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','8899','Other social work activities without accommodation n.e.c.','Q')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9001','Performing arts','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9002','Support activities to performing arts','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9003','Artistic creation','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9004','Operation of arts facilities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9101','Library and archives activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9102','Museums activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9103','Operation of historical sites and buildings and similar visitor attractions','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9104','Botanical and zoological gardens and nature reserves activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9200','Gambling and betting activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9311','Operation of sports facilities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9312','Activities of sports clubs','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9313','Fitness facilities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9319','Other sports activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9321','Activities of amusement parks and theme parks','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9329','Other amusement and recreation activities','R')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9411','Activities of business and employers membership organisations','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9412','Activities of professional membership organisations','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9420','Activities of trade unions','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9491','Activities of religious organisations','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9492','Activities of political organisations','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9499','Activities of other membership organisations n.e.c.','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9511','Repair of computers and peripheral equipment','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9512','Repair of communication equipment','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9521','Repair of consumer electronics','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9522','Repair of household appliances and home and garden equipment','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9523','Repair of footwear and leather goods','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9524','Repair of furniture and home furnishings','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9525','Repair of watches, clocks and jewellery','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9529','Repair of other personal and household goods','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9601','Washing and (dry-)cleaning of textile and fur products','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9602','Hairdressing and other beauty treatment','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9603','Funeral and related activities','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9604','Physical well-being activities','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9609','Other personal service activities n.e.c.','S')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9700','Activities of households as employers of domestic personnel','T')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9810','Undifferentiated goods-producing activities of private households for own use','T')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9820','Undifferentiated service-producing activities of private households for own use','T')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9900','Activities of extraterritorial organisations and bodies','U')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9901','Customer without credit exposure','')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','9902','unknown at the Time of customer creation (only for temporary Use!)','')
INSERT INTO general_register (id_register, id_key, value, val_char)VALUES ('P_EVAL_KATEG2','0000','Private Individuals','')
