<?xml version='1.0' encoding='utf-8' ?>
<field_list>
<field grid_searchtype="1" sort_order="1" field_name="id" header_name="Id" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="2" field_name="id_izvjestaja" header_name="Id izvjestaja" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="3" field_name="osoba" header_name="Osoba" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="4" field_name="datum_stanja" header_name="Datum stanja" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="5" field_name="institucija" header_name="Institucija" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="6" field_name="ogranicenje_obrade" header_name="Ograničenje obrade" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="7" field_name="oznaka_obveze" header_name="Oznaka obveze" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="8" field_name="oznaka_okvira" header_name="Oznaka okvira" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="9" field_name="oznaka_garancije" header_name="Oznaka garancije" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="10" field_name="subvencija" header_name="Subvencija" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="11" field_name="sindikat" header_name="Sindikat" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="12" field_name="tudja_sredstva" header_name="Tuđa sredstva" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="13" field_name="zalog_nekretnina" header_name="Zalog nekretnina" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="14" field_name="instrument_naplate" header_name="Instrument naplate" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="15" field_name="datum_obveze" header_name="Datum obveze" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="16" field_name="datum_obnove_iznosa" header_name="Datum obnove iznosa" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="17" field_name="datum_isteka_obveze" header_name="Datum isteka obveze" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="18" field_name="iznos_obveze" header_name="Iznos obveze" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="19" field_name="ugovorna_valuta" header_name="Ugovorna valuta" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="20" field_name="uloga" header_name="Uloga" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="21" field_name="vrsta_obveze" header_name="Vrsta obveze" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="22" field_name="vrsta_otplate" header_name="Vrsta otplate" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="23" field_name="iznos_rate" header_name="Iznos rate" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="24" field_name="iznos_glavnice" header_name="Iznos glavnice" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="25" field_name="iznos_kamate" header_name="Iznos kamate" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="26" field_name="iznos_ostatka" header_name="Iznos ostatka" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="27" field_name="ucestalost_placanja_g" header_name="Ucestalost plaćanja glavnice" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="28" field_name="ucestalost_placanja_k" header_name="Ucestalost plaćanja kamate" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="29" field_name="status_obveze" header_name="Status obveze" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="30" field_name="bud_glavnica" header_name="Bud glavnica" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="31" field_name="bud_kamata" header_name="Bud kamata" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="32" field_name="neiskoristeni_iznos" header_name="Neiskorišteni iznos" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="33" field_name="iskoristeni_iznos" header_name="Iskorišteni iznos" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="34" field_name="prekoraceni_iznos" header_name="Prekoračeni iznos" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="35" field_name="p_zadnja_3m" header_name="Prosjek zadnja 3M" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="36" field_name="p_zadnja_6m" header_name="Prosjek zadnja 6M" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="37" field_name="p_zadnja_12m" header_name="Prosjek zadnjih 12M" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="38" field_name="datum_zatvaranja" header_name="Datum zatvaranja" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="39" field_name="dana_kasnjenja" header_name="Dana kašnjenja" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="40" field_name="iznos_odr" header_name="Iznos ODR" control_type="TextBox" field_width="100" field_format="gccif" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="41" field_name="valuta_odr" header_name="Valuta ODR" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="42" field_name="datum_poceka" header_name="Datum počeka" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="43" field_name="datum_isteka_poceka" header_name="Datum isteka počeka" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="44" field_name="datum_moratorij" header_name="Datum moratorija" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="45" field_name="datum_isteka_moratorij" header_name="Datum isteka moratorija" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="ttod(@Field)" exists_sql="0" sort_sql="0" />
<field grid_searchtype="1" sort_order="46" field_name="ukupno_moratorij" header_name="Ukupno moratorij" control_type="TextBox" field_width="100" field_format="" field_alignment="3" back_color="255,255,255" fore_color="0,0,0" font_bold="0" field_function="" exists_sql="0" sort_sql="0" />
</field_list>

local lnid_izvjestaja
lnid_izvjestaja = rezultat.id
Select * From rezultat1 where id_izvjestaja = lnid_izvjestaja into cursor osr_ki_izvjestaj
GF_DataPreview("osr_ki_izvjestaj", "", "frm_osr_ki_i", "Kreditni izvještaji po upitu " + allt(trans(lnid_izvjestaja)))