*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="izterjave_maska.scx" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*
*
#INCLUDE "..\includes\locs.h"

DEFINE CLASS dataenvironment AS dataenvironment 
 	*< CLASSDATA: Baseclass="dataenvironment" Timestamp="" Scale="" Uniqueid="" ClassIcon="2" />

	Name = "Dataenvironment"

ENDDEFINE

DEFINE CLASS izterjave_maska AS gform OF "..\classes\gkclass.vcx" 
 	*< CLASSDATA: Baseclass="form" Timestamp="" Scale="" Uniqueid="" />

	*-- OBJECTDATA items order determines ZOrder / El orden de los items OBJECTDATA determina el ZOrder 
	*< OBJECTDATA: ObjPath="shpAgencija" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="shpPlan" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="shpPogodba" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtNazIdAgenc" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="tlbDogodki" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDatDogov" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIdAgenc" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatDogov" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblPlacDogov" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtPlacDogov" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblToDo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIzvedeno" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="edtToDo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIzvedeno" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtRok" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblRok" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIdDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatVnosa" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="edtOpisDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIdPog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cboIdTipDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cboIdVrsDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="edtOpombe" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblPlan" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkZobr" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDatDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDatVnosa" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdVrsDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdTipDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdPog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtPredNaj" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtNacinLeas" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtAneks" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtStatus" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtStatusAkt" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblNazIdPoroka" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtNazIdPoroka" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtid_val_debit" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblSplPog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtSplPog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDatumOdp" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatumOdp" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdDob" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtNazIdDob" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDebit" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDebit" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDatZap" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblStObrokovDolg" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtStObrokovDolg" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatZap" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdKupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIdKupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtNazIdKupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDolgKupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDolgKupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblNaDan" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatDolg" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDolgDatD" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblKontOseba" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtKontOseba" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblTelKo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtTelKo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblVnesel" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDatDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cboVnesel" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblObdeluje" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cboObdeluje" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblSkladisce" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtSkladisce" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="shpKontrole" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkDetektiv" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkOdvzem" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkProdano" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkPrisPorav" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkStecaj" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkOdvetnik" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkOdpisTerj" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkTozba" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="chkUkraden" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdAgenc" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblPredanoA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblVrnjenoA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblZakljucA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtPredanoA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtVrnjenoA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtZakljucA" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblGsmKo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtGsmKo" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtid_val_dolg_danes_bzobr" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtid_val_dog_zn" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblDolgKupcaBrezZobr" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtDolgKupcaBrezZobr" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtid_val_dolg_kupca" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtid_val_dolg_dat_d" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cmdOpombe" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="lblIdSsPostopek" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="txtIdSsPostopek" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="cmdOpisDog" UniqueID="" Timestamp="" />
	*< OBJECTDATA: ObjPath="tmrDolg" UniqueID="" Timestamp="" />

	*<DefinedPropArrayMethod>
		*m: izracunaj_dolg_all		&& Mth. za izraèun dolga
		*p: id_ss_postopek		&& id from table ss_postopek
		*p: is_support_user		&& told us if we are support user
		*p: izracunaj_dolg		&& Ali je potrebno izraèunati dolg - npr. ob spremembi partnerja
		*p: izracunaj_dolg_id_kupca		&& Šifra partnarja za izraèun dolga
		*p: opombe_old
	*</DefinedPropArrayMethod>

	Caption = "Podrobnosti dogodka"
	DataSession = 2
	DoCreate = .T.
	Height = 566
	izracunaj_dolg = .T.		&& Ali je potrebno izraèunati dolg - npr. ob spremembi partnerja
	izracunaj_dolg_id_kupca = 		&& Šifra partnarja za izraèun dolga
	Left = -1
	Name = "IZTERJAVE_MASKA"
	Top = 0
	Width = 763
	WindowState = 0
	tmrClick.Left = 660
	tmrClick.Name = "tmrClick"
	tmrClick.Top = 510

	ADD OBJECT 'cboIdTipDog' AS bcombolist WITH ;
		BoundColumn = 2, ;
		ControlSource = "ss_dogodek.id_tip_dog", ;
		Height = 19, ;
		Left = 110, ;
		Name = "cboIdTipDog", ;
		obvezen = .T., ;
		RowSource = "ss_tipi_dog.opis,id_tip_dog", ;
		RowSourceType = 2, ;
		TabIndex = 10, ;
		Top = 30, ;
		Width = 135, ;
		ZOrderSet = 23
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="combobox" />

	ADD OBJECT 'cboIdVrsDog' AS bcombolist WITH ;
		BoundColumn = 2, ;
		ControlSource = "ss_dogodek.id_vrs_dog", ;
		Height = 19, ;
		Left = 400, ;
		Name = "cboIdVrsDog", ;
		RowSource = "ss_vrst_dog.opis,id_vrs_dog", ;
		RowSourceType = 2, ;
		TabIndex = 12, ;
		Top = 30, ;
		Width = 203, ;
		ZOrderSet = 23
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="combobox" />

	ADD OBJECT 'cboObdeluje' AS bcombolist WITH ;
		BackColor = 187,221,255, ;
		BoundColumn = 2, ;
		ControlSource = "ss_dogodek.obdeluje", ;
		Height = 19, ;
		Left = 333, ;
		Name = "cboObdeluje", ;
		obvezen = .T., ;
		RowSource = "users.user_desc,username", ;
		RowSourceType = 2, ;
		TabIndex = 57, ;
		Top = 295, ;
		Width = 157, ;
		ZOrderSet = 61
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="combobox" />

	ADD OBJECT 'cboVnesel' AS bcombolist WITH ;
		BoundColumn = 2, ;
		ControlSource = "ss_dogodek.vnesel", ;
		DisabledForeColor = 128,0,64, ;
		Enabled = .F., ;
		Height = 19, ;
		Left = 113, ;
		Name = "cboVnesel", ;
		RowSource = "users_all.user_desc,username", ;
		RowSourceType = 2, ;
		TabIndex = 55, ;
		Top = 295, ;
		Width = 160, ;
		ZOrderSet = 59
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="combobox" />

	ADD OBJECT 'chkDetektiv' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Detektiv", ;
		ControlSource = "ss_dogodek.detektiv", ;
		Left = 505, ;
		Name = "chkDetektiv", ;
		TabIndex = 62, ;
		Top = 155, ;
		Value = .F., ;
		ZOrderSet = 65
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkOdpisTerj' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Odpis ter.", ;
		ControlSource = "ss_dogodek.odpis_terj", ;
		Left = 680, ;
		Name = "chkOdpisTerj", ;
		TabIndex = 68, ;
		Top = 155, ;
		Value = .F., ;
		ZOrderSet = 71
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkOdvetnik' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Odvetnik", ;
		ControlSource = "ss_dogodek.odvetnik", ;
		Left = 585, ;
		Name = "chkOdvetnik", ;
		TabIndex = 67, ;
		Top = 195, ;
		Value = .F., ;
		ZOrderSet = 70
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkOdvzem' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Odvzem", ;
		ControlSource = "ss_dogodek.odvzem", ;
		Left = 505, ;
		Name = "chkOdvzem", ;
		TabIndex = 63, ;
		Top = 175, ;
		Value = .F., ;
		ZOrderSet = 66
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkPrisPorav' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Prisilna por.", ;
		ControlSource = "ss_dogodek.pris_porav", ;
		Left = 585, ;
		Name = "chkPrisPorav", ;
		TabIndex = 65, ;
		Top = 155, ;
		Value = .F., ;
		ZOrderSet = 68
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkProdano' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Prodano", ;
		ControlSource = "ss_dogodek.prodano", ;
		Left = 505, ;
		Name = "chkProdano", ;
		TabIndex = 64, ;
		Top = 195, ;
		Value = .F., ;
		ZOrderSet = 67
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkStecaj' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Steèaj", ;
		ControlSource = "ss_dogodek.stecaj", ;
		Left = 585, ;
		Name = "chkStecaj", ;
		TabIndex = 66, ;
		Top = 175, ;
		Value = .F., ;
		ZOrderSet = 69
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkTozba' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Tožba", ;
		ControlSource = "ss_dogodek.tozba", ;
		Left = 680, ;
		Name = "chkTozba", ;
		TabIndex = 69, ;
		Top = 175, ;
		Value = .F., ;
		ZOrderSet = 72
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkUkraden' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "Ukraden", ;
		ControlSource = "ss_dogodek.ukraden", ;
		Left = 680, ;
		Name = "chkUkraden", ;
		TabIndex = 70, ;
		Top = 195, ;
		Value = .F., ;
		ZOrderSet = 73
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'chkZobr' AS bcheck WITH ;
		AutoSize = .T., ;
		Caption = "ZOBR", ;
		Enabled = .F., ;
		Left = 545, ;
		Name = "chkZobr", ;
		TabIndex = 8, ;
		Top = 11, ;
		ZOrderSet = 26
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="checkbox" />

	ADD OBJECT 'cmdOpisDog' AS commandbutton WITH ;
		Caption = "Opis dogodka", ;
		Height = 25, ;
		Left = 13, ;
		Name = "cmdOpisDog", ;
		TabIndex = 60, ;
		Top = 338, ;
		Width = 96
		*< END OBJECT: BaseClass="commandbutton" />

	ADD OBJECT 'cmdOpombe' AS commandbutton WITH ;
		Caption = "Opombe", ;
		Height = 27, ;
		Left = 5, ;
		Name = "cmdOpombe", ;
		TabIndex = 91, ;
		Top = 451, ;
		Width = 75
		*< END OBJECT: BaseClass="commandbutton" />

	ADD OBJECT 'edtOpisDog' AS beditbox WITH ;
		BackColor = 255,240,240, ;
		ControlSource = "ss_dogodek.opis_dog", ;
		Height = 45, ;
		Left = 113, ;
		Margin = 0, ;
		Name = "edtOpisDog", ;
		TabIndex = 61, ;
		Top = 335, ;
		Width = 377, ;
		ZOrderSet = 21
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="editbox" />

	ADD OBJECT 'edtOpombe' AS beditbox WITH ;
		ControlSource = "ss_dogodek.opombe", ;
		ForeColor = 128,0,64, ;
		Height = 80, ;
		Left = 5, ;
		Name = "edtOpombe", ;
		ReadOnly = .T., ;
		TabIndex = 92, ;
		TabStop = .F., ;
		Top = 480, ;
		Width = 755, ;
		ZOrderSet = 24
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="editbox" />

	ADD OBJECT 'edtToDo' AS beditbox WITH ;
		BackColor = 255,255,225, ;
		ControlSource = "ss_dogodek.to_do", ;
		Height = 19, ;
		Left = 80, ;
		Margin = 0, ;
		MaxLength = 500, ;
		Name = "edtToDo", ;
		TabIndex = 86, ;
		Top = 410, ;
		Width = 672, ;
		ZOrderSet = 13
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="editbox" />

	ADD OBJECT 'lblDatDog' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Datum dogodka", ;
		Height = 17, ;
		Left = 252, ;
		Name = "lblDatDog", ;
		TabIndex = 5, ;
		Top = 52, ;
		Width = 146, ;
		ZOrderSet = 27
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDatDogov' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dogov. dat. plaè.", ;
		Height = 17, ;
		Left = 468, ;
		Name = "lblDatDogov", ;
		TabIndex = 89, ;
		Top = 436, ;
		Width = 144, ;
		ZOrderSet = 6
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDatumOdp' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dat. izdaje odp.", ;
		Left = 530, ;
		Name = "lblDatumOdp", ;
		TabIndex = 34, ;
		Top = 101, ;
		Width = 144, ;
		ZOrderSet = 38
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDatVnosa' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Datum vnosa dogodka", ;
		Height = 17, ;
		Left = 250, ;
		Name = "lblDatVnosa", ;
		TabIndex = 6, ;
		Top = 11, ;
		Width = 146, ;
		ZOrderSet = 27
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDatZap' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dat. zapad. nasl. obr.", ;
		Height = 17, ;
		Left = 530, ;
		Name = "lblDatZap", ;
		TabIndex = 36, ;
		Top = 121, ;
		Width = 144, ;
		ZOrderSet = 44
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDebit' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Znesek obroka", ;
		Height = 17, ;
		Left = 273, ;
		Name = "lblDebit", ;
		TabIndex = 32, ;
		Top = 121, ;
		Width = 110, ;
		ZOrderSet = 43
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDolgKupca' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dolg danes (DOMV)", ;
		Height = 17, ;
		Left = 3, ;
		Name = "lblDolgKupca", ;
		TabIndex = 42, ;
		Top = 172, ;
		Width = 109, ;
		ZOrderSet = 49
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblDolgKupcaBrezZobr' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dolg danes brez ZOBR (DOMV)", ;
		Height = 17, ;
		Left = 0, ;
		Name = "lblDolgKupcaBrezZobr", ;
		TabIndex = 41, ;
		Top = 193, ;
		Width = 293, ;
		ZOrderSet = 49
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblGsmKo' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "GSM", ;
		Left = 0, ;
		Name = "lblGsmKo", ;
		TabIndex = 52, ;
		Top = 277, ;
		Width = 109, ;
		ZOrderSet = 56
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdAgenc' AS blabel WITH ;
		Caption = "Agencija", ;
		FontBold = .T., ;
		Left = 505, ;
		Name = "lblIdAgenc", ;
		TabIndex = 71, ;
		Top = 226, ;
		ZOrderSet = 74
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdDob' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dobavitelj", ;
		Height = 17, ;
		Left = 6, ;
		Name = "lblIdDob", ;
		TabIndex = 23, ;
		Top = 121, ;
		Width = 64, ;
		ZOrderSet = 40
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdDog' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Št. dogodka", ;
		Left = 6, ;
		Name = "lblIdDog", ;
		TabIndex = 2, ;
		Top = 11, ;
		Width = 100, ;
		ZOrderSet = 19
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdKupca' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Šif. partnerja", ;
		Left = 3, ;
		Name = "lblIdKupca", ;
		TabIndex = 38, ;
		Top = 152, ;
		Width = 109, ;
		ZOrderSet = 46
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdPog' AS blabel WITH ;
		Caption = "Pogodba", ;
		FontBold = .T., ;
		Left = 15, ;
		Name = "lblIdPog", ;
		TabIndex = 13, ;
		Top = 76, ;
		ZOrderSet = 29
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdSsPostopek' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Št. postopka", ;
		Height = 17, ;
		Left = 6, ;
		Name = "lblIdSsPostopek", ;
		TabIndex = 1, ;
		Top = 52, ;
		Width = 100
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdTipDog' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Tip dogodka", ;
		Height = 17, ;
		Left = 6, ;
		Name = "lblIdTipDog", ;
		TabIndex = 9, ;
		Top = 32, ;
		Width = 100, ;
		ZOrderSet = 28
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIdVrsDog' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Vrsta dogodka", ;
		Height = 17, ;
		Left = 250, ;
		Name = "lblIdVrsDog", ;
		TabIndex = 11, ;
		Top = 32, ;
		Width = 146, ;
		ZOrderSet = 28
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblIzvedeno' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Izvedeno", ;
		Height = 17, ;
		Left = 514, ;
		Name = "lblIzvedeno", ;
		TabIndex = 83, ;
		Top = 386, ;
		Width = 98, ;
		ZOrderSet = 12
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblKontOseba' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Kontaktna oseba", ;
		Left = 0, ;
		Name = "lblKontOseba", ;
		TabIndex = 48, ;
		Top = 237, ;
		Width = 109, ;
		ZOrderSet = 54
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblNaDan' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Na", ;
		Height = 17, ;
		Left = 252, ;
		Name = "lblNaDan", ;
		TabIndex = 45, ;
		Top = 172, ;
		Width = 26, ;
		ZOrderSet = 51
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblNazIdPoroka' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Porok", ;
		Left = 6, ;
		Name = "lblNazIdPoroka", ;
		TabIndex = 21, ;
		Top = 101, ;
		Width = 64, ;
		ZOrderSet = 34
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblObdeluje' AS blabel WITH ;
		Caption = "Obdeluje", ;
		Left = 278, ;
		Name = "lblObdeluje", ;
		TabIndex = 56, ;
		Top = 297, ;
		ZOrderSet = 60
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblPlacDogov' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Dogovorjeni znesek", ;
		Height = 17, ;
		Left = 210, ;
		Name = "lblPlacDogov", ;
		TabIndex = 87, ;
		Top = 435, ;
		Width = 135, ;
		ZOrderSet = 9
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblPlan' AS blabel WITH ;
		Caption = "Plan za naprej", ;
		FontBold = .T., ;
		Left = 15, ;
		Name = "lblPlan", ;
		TabIndex = 80, ;
		Top = 386, ;
		ZOrderSet = 25
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblPredanoA' AS blabel WITH ;
		Caption = "Predano", ;
		Left = 505, ;
		Name = "lblPredanoA", ;
		TabIndex = 74, ;
		Top = 250, ;
		ZOrderSet = 75
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblRok' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Rok", ;
		Height = 17, ;
		Left = 294, ;
		Name = "lblRok", ;
		TabIndex = 81, ;
		Top = 363, ;
		Width = 51, ;
		ZOrderSet = 16
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblSkladisce' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Skladišèeno pri", ;
		Left = 0, ;
		Name = "lblSkladisce", ;
		TabIndex = 58, ;
		Top = 317, ;
		Width = 109, ;
		ZOrderSet = 62
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblSplPog' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Splošni pogoji", ;
		Left = 273, ;
		Name = "lblSplPog", ;
		TabIndex = 25, ;
		Top = 101, ;
		Width = 110, ;
		ZOrderSet = 36
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblStObrokovDolg' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Št. obrokov - celotni dolg", ;
		Height = 17, ;
		Left = 0, ;
		Name = "lblStObrokovDolg", ;
		TabIndex = 41, ;
		Top = 213, ;
		Width = 293, ;
		ZOrderSet = 49
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblTelKo' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Telefon", ;
		Left = 0, ;
		Name = "lblTelKo", ;
		TabIndex = 50, ;
		Top = 257, ;
		Width = 109, ;
		ZOrderSet = 56
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblToDo' AS blabel WITH ;
		Caption = "Narediti", ;
		Left = 31, ;
		Name = "lblToDo", ;
		TabIndex = 85, ;
		Top = 411, ;
		ZOrderSet = 11
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblVnesel' AS blabel WITH ;
		Alignment = 1, ;
		AutoSize = .F., ;
		Caption = "Vnesel", ;
		Left = 0, ;
		Name = "lblVnesel", ;
		TabIndex = 54, ;
		Top = 297, ;
		Width = 109, ;
		ZOrderSet = 58
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblVrnjenoA' AS blabel WITH ;
		Caption = "Vrnjeno", ;
		Left = 590, ;
		Name = "lblVrnjenoA", ;
		TabIndex = 76, ;
		Top = 250, ;
		ZOrderSet = 76
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'lblZakljucA' AS blabel WITH ;
		Caption = "Zakljuèeno", ;
		Left = 675, ;
		Name = "lblZakljucA", ;
		TabIndex = 78, ;
		Top = 250, ;
		ZOrderSet = 77
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="label" />

	ADD OBJECT 'shpAgencija' AS shape WITH ;
		Height = 60, ;
		Left = 495, ;
		Name = "shpAgencija", ;
		SpecialEffect = 0, ;
		Top = 235, ;
		Width = 265, ;
		ZOrderSet = 0
		*< END OBJECT: BaseClass="shape" />

	ADD OBJECT 'shpKontrole' AS shape WITH ;
		Height = 70, ;
		Left = 495, ;
		Name = "shpKontrole", ;
		SpecialEffect = 0, ;
		Top = 150, ;
		Width = 265, ;
		ZOrderSet = 64
		*< END OBJECT: BaseClass="shape" />

	ADD OBJECT 'shpPlan' AS shape WITH ;
		Height = 50, ;
		Left = 5, ;
		Name = "shpPlan", ;
		SpecialEffect = 0, ;
		Top = 395, ;
		Width = 755, ;
		ZOrderSet = 1
		*< END OBJECT: BaseClass="shape" />

	ADD OBJECT 'shpPogodba' AS shape WITH ;
		Height = 60, ;
		Left = 5, ;
		Name = "shpPogodba", ;
		SpecialEffect = 0, ;
		Top = 85, ;
		Width = 755, ;
		ZOrderSet = 2
		*< END OBJECT: BaseClass="shape" />

	ADD OBJECT 'tlbDogodki' AS toolbar_sifr WITH ;
		ButtonCount = 5, ;
		Left = 625, ;
		Name = "tlbDogodki", ;
		TabIndex = 93, ;
		Top = 10, ;
		Width = 135, ;
		ZOrderSet = 4, ;
		BTNEXIT.Left = 30, ;
		BTNEXIT.Name = "BTNEXIT", ;
		BTNEXIT.Top = 5, ;
		BTNSAVE.Left = 5, ;
		BTNSAVE.Name = "BTNSAVE", ;
		BTNSAVE.Picture = ..\bmps\save.bmp, ;
		BTNSAVE.Top = 5, ;
		btnToolTip.Left = 55, ;
		btnToolTip.Name = "btnToolTip", ;
		btnToolTip.Picture = ..\bmps\tool.bmp, ;
		btnToolTip.Top = 5, ;
		Command4.Caption = "", ;
		Command4.Height = 25, ;
		Command4.Left = 80, ;
		Command4.Name = "btnUnlock", ;
		Command4.Picture = ..\bmps\unliquid.bmp, ;
		Command4.ToolTipText = "Odkleni dogodek", ;
		Command4.Top = 5, ;
		Command4.Width = 25, ;
		Command5.Caption = "", ;
		Command5.Enabled = .F., ;
		Command5.Height = 25, ;
		Command5.Left = 105, ;
		Command5.Name = "btnContractStatusChange", ;
		Command5.Picture = ..\bmps\run.bmp, ;
		Command5.ToolTipText = "Spremeni status na pogodbi", ;
		Command5.Top = 5, ;
		Command5.Width = 25
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="commandgroup" />

	ADD OBJECT 'tmrDolg' AS timer WITH ;
		Enabled = .F., ;
		Height = 23, ;
		Interval = 1000, ;
		Left = 732, ;
		Name = "tmrDolg", ;
		Top = 456, ;
		Width = 23
		*< END OBJECT: BaseClass="timer" />

	ADD OBJECT 'txtAneks' AS btextro WITH ;
		Height = 19, ;
		Left = 420, ;
		Name = "txtAneks", ;
		TabIndex = 18, ;
		Top = 75, ;
		Width = 25, ;
		ZOrderSet = 32
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatDog' AS btext WITH ;
		ControlSource = "ss_dogodek.datum_dogodka", ;
		Height = 19, ;
		Left = 400, ;
		Name = "txtDatDog", ;
		TabIndex = 14, ;
		Top = 49, ;
		Width = 140, ;
		ZOrderSet = 63
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatDogov' AS datum WITH ;
		ControlSource = "ss_dogodek.dat_dogov", ;
		Left = 615, ;
		Name = "txtDatDogov", ;
		TabIndex = 90, ;
		Top = 435, ;
		ZOrderSet = 8
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatDolg' AS datum WITH ;
		BorderColor = 120,120,120, ;
		ControlSource = "ss_dogodek.dat_dolg", ;
		DisabledForeColor = 0,0,0, ;
		Enabled = .F., ;
		FontBold = .T., ;
		Height = 18, ;
		Left = 280, ;
		Name = "txtDatDolg", ;
		SpecialEffect = 1, ;
		TabIndex = 46, ;
		Top = 171, ;
		Width = 74, ;
		ZOrderSet = 52
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatumOdp' AS datum WITH ;
		Enabled = .F., ;
		Left = 678, ;
		Name = "txtDatumOdp", ;
		TabIndex = 35, ;
		Top = 100, ;
		ZOrderSet = 39
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatVnosa' AS btextro WITH ;
		ControlSource = "ss_dogodek.dat_vnosa", ;
		Enabled = .F., ;
		Left = 400, ;
		Name = "txtDatVnosa", ;
		TabIndex = 7, ;
		Top = 9, ;
		Width = 140, ;
		ZOrderSet = 20
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDatZap' AS datum WITH ;
		Enabled = .F., ;
		Left = 678, ;
		Name = "txtDatZap", ;
		TabIndex = 37, ;
		Top = 120, ;
		ZOrderSet = 45
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDebit' AS btextro WITH ;
		Alignment = 3, ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 385, ;
		Name = "txtDebit", ;
		TabIndex = 33, ;
		Top = 120, ;
		Value = 0, ;
		Width = 110, ;
		ZOrderSet = 42
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDolgDatD' AS btextro WITH ;
		ControlSource = "ss_dogodek.dolg_dat_d", ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 353, ;
		Name = "txtDolgDatD", ;
		TabIndex = 47, ;
		Top = 170, ;
		Width = 105, ;
		ZOrderSet = 53
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDolgKupca' AS btextro WITH ;
		Alignment = 3, ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 113, ;
		Name = "txtDolgKupca", ;
		TabIndex = 44, ;
		ToolTipText = "Zapadlo neplaèano iz plana plaèil s fiktivnimi zamudnimi obrestmi", ;
		Top = 170, ;
		Value = 0, ;
		Width = 106, ;
		ZOrderSet = 50
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtDolgKupcaBrezZobr' AS btextro WITH ;
		Alignment = 3, ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 298, ;
		Name = "txtDolgKupcaBrezZobr", ;
		TabIndex = 43, ;
		ToolTipText = "Zapadlo neplaèano iz dnevnega posnetka stanja brez fiktivnih zamudnih obresti", ;
		Top = 191, ;
		Value = 0, ;
		Width = 160, ;
		ZOrderSet = 50
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtGsmKo' AS btext WITH ;
		ControlSource = "ss_dogodek.gsm_ko", ;
		Height = 19, ;
		Left = 113, ;
		Name = "txtGsmKo", ;
		TabIndex = 53, ;
		Top = 275, ;
		Width = 377, ;
		ZOrderSet = 57
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtid_val_debit' AS btextro WITH ;
		Alignment = 0, ;
		Height = 19, ;
		Left = 496, ;
		Name = "txtid_val_debit", ;
		TabIndex = 27, ;
		Top = 120, ;
		Width = 33, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtid_val_dog_zn' AS btextro WITH ;
		Alignment = 0, ;
		Height = 19, ;
		Left = 453, ;
		Name = "txtid_val_dog_zn", ;
		TabIndex = 26, ;
		Top = 434, ;
		Width = 33, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtid_val_dolg_danes_bzobr' AS btextro WITH ;
		Alignment = 0, ;
		Height = 19, ;
		Left = 458, ;
		Name = "txtid_val_dolg_danes_bzobr", ;
		TabIndex = 28, ;
		Top = 191, ;
		Width = 33, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtid_val_dolg_dat_d' AS btextro WITH ;
		Alignment = 0, ;
		Height = 19, ;
		Left = 458, ;
		Name = "txtid_val_dolg_dat_d", ;
		TabIndex = 30, ;
		Top = 170, ;
		Width = 33, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtid_val_dolg_kupca' AS btextro WITH ;
		Alignment = 0, ;
		Height = 19, ;
		Left = 219, ;
		Name = "txtid_val_dolg_kupca", ;
		TabIndex = 31, ;
		Top = 170, ;
		Width = 33, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIdAgenc' AS btext WITH ;
		ControlSource = "ss_dogodek.id_agenc", ;
		Height = 19, ;
		Left = 560, ;
		Name = "txtIdAgenc", ;
		TabIndex = 72, ;
		Top = 225, ;
		Width = 25, ;
		ZOrderSet = 7
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIdDog' AS btextro WITH ;
		ControlSource = "ss_dogodek.id_dog", ;
		Height = 19, ;
		Left = 110, ;
		Name = "txtIdDog", ;
		TabIndex = 3, ;
		Top = 9, ;
		Width = 135, ;
		ZOrderSet = 17
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIdKupca' AS btext WITH ;
		ControlSource = "ss_dogodek.id_kupca", ;
		Height = 19, ;
		Left = 113, ;
		Name = "txtIdKupca", ;
		obvezen = .T., ;
		TabIndex = 39, ;
		Top = 150, ;
		update_disabled = .T., ;
		Width = 70, ;
		ZOrderSet = 47
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIdPog' AS btext WITH ;
		Left = 80, ;
		Name = "txtIdPog", ;
		TabIndex = 15, ;
		Top = 75, ;
		update_disabled = .T., ;
		ZOrderSet = 22
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIdSsPostopek' AS btextro WITH ;
		ControlSource = "ss_dogodek.id_ss_postopek", ;
		Height = 19, ;
		Left = 110, ;
		Name = "txtIdSsPostopek", ;
		TabIndex = 4, ;
		Top = 51, ;
		Width = 135
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtIzvedeno' AS btext WITH ;
		BackColor = 200,255,200, ;
		ControlSource = "ss_dogodek.izvedeno", ;
		Left = 615, ;
		Name = "txtIzvedeno", ;
		TabIndex = 84, ;
		Top = 385, ;
		Width = 140, ;
		ZOrderSet = 14
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtKontOseba' AS btext WITH ;
		ControlSource = "ss_dogodek.kont_oseba", ;
		Height = 19, ;
		Left = 113, ;
		Name = "txtKontOseba", ;
		TabIndex = 49, ;
		Top = 235, ;
		Width = 377, ;
		ZOrderSet = 55
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtNacinLeas' AS btextro WITH ;
		Height = 19, ;
		Left = 390, ;
		Name = "txtNacinLeas", ;
		TabIndex = 17, ;
		Top = 75, ;
		Width = 25, ;
		ZOrderSet = 31
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtNazIdAgenc' AS btextro WITH ;
		Height = 19, ;
		Left = 590, ;
		Name = "txtNazIdAgenc", ;
		TabIndex = 73, ;
		Top = 225, ;
		Width = 160, ;
		ZOrderSet = 3
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtNazIdDob' AS btextro WITH ;
		Height = 19, ;
		Left = 72, ;
		Name = "txtNazIdDob", ;
		TabIndex = 24, ;
		Top = 120, ;
		Width = 200, ;
		ZOrderSet = 41
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtNazIdKupca' AS btextro WITH ;
		Height = 19, ;
		Left = 183, ;
		Name = "txtNazIdKupca", ;
		TabIndex = 40, ;
		Top = 150, ;
		Width = 308, ;
		ZOrderSet = 48
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtNazIdPoroka' AS btextro WITH ;
		Height = 19, ;
		Left = 72, ;
		Name = "txtNazIdPoroka", ;
		TabIndex = 22, ;
		Top = 100, ;
		Width = 200, ;
		ZOrderSet = 35
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtPlacDogov' AS btext WITH ;
		ControlSource = "ss_dogodek.plac_dogov", ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 350, ;
		Name = "txtPlacDogov", ;
		TabIndex = 88, ;
		Top = 434, ;
		Width = 102, ;
		ZOrderSet = 10
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtPredanoA' AS datum WITH ;
		ControlSource = "ss_dogodek.predano_a", ;
		Left = 505, ;
		Name = "txtPredanoA", ;
		TabIndex = 75, ;
		Top = 270, ;
		ZOrderSet = 78
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtPredNaj' AS btextro WITH ;
		Height = 19, ;
		Left = 185, ;
		Name = "txtPredNaj", ;
		TabIndex = 16, ;
		Top = 75, ;
		Width = 200, ;
		ZOrderSet = 30
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtRok' AS btext WITH ;
		ControlSource = "ss_dogodek.rok", ;
		Left = 350, ;
		Name = "txtRok", ;
		TabIndex = 82, ;
		Top = 385, ;
		Width = 140, ;
		ZOrderSet = 15
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtSkladisce' AS btext WITH ;
		ControlSource = "ss_dogodek.skladisce", ;
		Height = 19, ;
		Left = 113, ;
		Name = "txtSkladisce", ;
		TabIndex = 59, ;
		Top = 315, ;
		Width = 377, ;
		ZOrderSet = 63
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtSplPog' AS btextro WITH ;
		Height = 19, ;
		Left = 385, ;
		Name = "txtSplPog", ;
		TabIndex = 29, ;
		Top = 100, ;
		Width = 60, ;
		ZOrderSet = 37
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtStatus' AS btextro WITH ;
		Height = 19, ;
		Left = 481, ;
		Name = "txtStatus", ;
		TabIndex = 20, ;
		Top = 75, ;
		Width = 266, ;
		ZOrderSet = 33
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtStatusAkt' AS btextro WITH ;
		Height = 19, ;
		Left = 450, ;
		Name = "txtStatusAkt", ;
		TabIndex = 19, ;
		Top = 75, ;
		Width = 25, ;
		ZOrderSet = 33
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtStObrokovDolg' AS btextro WITH ;
		Alignment = 3, ;
		Height = 19, ;
		InputMask = (m.gcCif), ;
		Left = 298, ;
		Name = "txtStObrokovDolg", ;
		TabIndex = 43, ;
		ToolTipText = "", ;
		Top = 211, ;
		Value = 0, ;
		Width = 160, ;
		ZOrderSet = 50
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtTelKo' AS btext WITH ;
		ControlSource = "ss_dogodek.tel_ko", ;
		Height = 19, ;
		Left = 113, ;
		Name = "txtTelKo", ;
		TabIndex = 51, ;
		Top = 255, ;
		Width = 377, ;
		ZOrderSet = 57
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtVrnjenoA' AS datum WITH ;
		ControlSource = "ss_dogodek.vrnjeno_a", ;
		Left = 590, ;
		Name = "txtVrnjenoA", ;
		TabIndex = 77, ;
		Top = 270, ;
		ZOrderSet = 79
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />

	ADD OBJECT 'txtZakljucA' AS datum WITH ;
		ControlSource = "ss_dogodek.zakljuc_a", ;
		Left = 675, ;
		Name = "txtZakljucA", ;
		TabIndex = 79, ;
		Top = 270, ;
		ZOrderSet = 80
		*< END OBJECT: ClassLib="..\classes\vclas1.vcx" BaseClass="textbox" />
	
	PROCEDURE Init
		LPARAMETERS tnIdKljuc, tnTip, tcIdKupca, tnIdCont, tlIsSupportUser, tnSsIdPostopek
		LOCAL lcIdKljuc, lnRokNaprej, lcSQL, laPar[1]
		
		WITH Thisform
			IF PCOUNT()=0 THEN 
				.tip_vnosne_maske=1 && dodajanje novega zapisa
			ELSE
				IF PCOUNT()=1 THEN 
					.tip_vnosne_maske=0 && pregled podatka
				ELSE
					.tip_vnosne_maske=m.tnTip
				ENDIF	
			ENDIF
				
			.is_support_user = tlIsSupportUser
			.id_ss_postopek = IIF(TYPE("tnSsIdPostopek") = "N", tnSsIdPostopek, NULL)
		
			IF .tip_vnosne_maske = 1 THEN && dodajanje novega zapisa
				GF_SQLEXEC("SELECT TOP 0 * FROM dbo.ss_dogodek ORDER BY id_dog","ss_dogodek")
				SELECT * FROM ss_dogodek INTO CURSOR _kopija_ss_dogodek
				
				lnRokNaprej = GF_SQLExecScalar("SELECT rok_naprej FROM dbo.ss_nastavit") && GOBJ_Settings.GetVal("rok_naprej")
			
				SELECT ss_dogodek
				APPEND BLANK 
				REPLACE ;
					id_ss_postopek WITH .id_ss_postopek, ;
					id_kupca WITH m.tcIdKupca, ;
					id_cont WITH m.tnIdCont, ;
					dolg_dat_d WITH 0, ;
					plac_dogov WITH 0, ;
					rok WITH DATE()+NVL(lnRokNaprej,0)+(1/3), ;
					dat_vnosa WITH DATETIME(), ;
					datum_dogodka WITH DATETIME(), ;
					zaklenjen WITH NULL, ;
					vnesel WITH GOBJ_COMM.GetUserName(), ;
					obdeluje WITH GOBJ_COMM.GetUserName()
			ELSE
				lcIdKljuc = TRANSFORM(m.tnIdKljuc)
				GF_SQLEXEC("SELECT * FROM dbo.ss_dogodek WHERE id_dog="+m.lcIdKljuc,"ss_dogodek")
				
				IF ISNULL(ss_dogodek.datum_dogodka)
					SELECT ss_dogodek
					REPLACE ;
						datum_dogodka WITH dat_vnosa
				ENDIF
				
				IF ISNULL(ss_dogodek.zaklenjen)
					SELECT * FROM ss_dogodek INTO CURSOR _kopija_ss_dogodek
				ELSE
					thisform.opombe_old = ss_dogodek.opombe
				ENDIF 
						
				* check, if user can change event, which is not of his
				IF .tip_vnosne_maske = 2 AND ss_dogodek.vnesel <> GOBJ_COMM.GetUserName() THEN
					IF GOBJ_Permissions.GetPermissionEx("SpecialServicesRecoveryReportEventUpdateAll", "EventType", ss_dogodek.id_tip_dog) < 2 THEN
						pozor(STRTRAN(PERMISSION_DENIED, "{0}", "SpecialServicesRecoveryReportEventUpdateAll"))
						RETURN .F.
					ENDIF
				ENDIF
			ENDIF
			
			* preveri in nastavi permission-e
			IF !.set_permissions() THEN
				RETURN .F.
			ENDIF
		
			* we need all users for combobox vnesel - not support users must see support users in combobox Vnesel
			TEXT TO lcSql NOSHOW 
				SELECT username, user_desc 
				FROM dbo.users 
				WHERE is_user = 1 AND inactive = 0 
				UNION 
				SELECT username, user_desc 
				FROM dbo.users 
				WHERE username= ?p1 
				ORDER BY user_desc
			ENDTEXT 
			laPar[1] = ss_dogodek.vnesel
			GF_SQLEXEC_P(lcSql, @laPar, "users_all")
		
			
			* check if current_user is support user then show all users
			IF .is_support_user = .F.
				TEXT TO lcSql NOSHOW 
					SELECT username, user_desc 
					FROM dbo.users 
					WHERE is_user = 1 AND inactive = 0 AND is_support = 0
					UNION 
					SELECT username, user_desc 
					FROM dbo.users 
					WHERE username= ?p1 
					ORDER BY user_desc
				ENDTEXT 
			ENDIF
			laPar[1] = ss_dogodek.obdeluje
			GF_SQLEXEC_P(lcSql, @laPar, "users")
			
			.set_controls
		ENDWITH 
	ENDPROC

	PROCEDURE izracunaj_dolg_all		&& Mth. za izraèun dolga
		LOCAL lcSqlDebt, lcText, lnRows, lnCols 
		
		lcText = "Izraèun dolga na dan" && caption
		lnRows = SROWS()/2.1
		lnCols = SCOLS()/2.3
		lcText = gcE + SPACE(20) + lcText + SPACE(20) + gcE
		
		
		WAIT lcText WINDOW AT lnRows, lnCols NOCLEAR NOWAIT
		Thisform.txtDolgKupca.Value = GF_GetDebt(Thisform.Izracunaj_dolg_id_kupca, .F., DATE(), "000", 0, "", .F., .T., .T.)
		
		* Calculate current debt for partner from planp_ds
		TEXT TO lcSqlDebt NOSHOW
			SELECT 
			    SUM(d.saldo) AS saldo 
			FROM (
			    SELECT DISTINCT id_cont, saldo
			    FROM dbo.gv_SS_Dogodek_View 
			    WHERE id_kupca = '{0}'
			    ) AS d
		ENDTEXT
		
		lcSqlDebt = STRTRAN(lcSqlDebt, "{0}", Thisform.Izracunaj_dolg_id_kupca)
		Thisform.txtDolgKupcaBrezZOBR.Value = GF_SQLExecScalarNull(lcSqlDebt)
		Thisform.txtStObrokovDolg.Value = GF_SumPartner_GetObrokov(Thisform.Izracunaj_dolg_id_kupca)
		
		IF Thisform.tip_vnosne_maske = 1 THEN 
			Thisform.txtDatDolg.Value = DATETIME()
			Thisform.txtDolgDatD.Value = Thisform.txtDolgKupca.Value
		ENDIF 
		
		WAIT CLEAR 
	ENDPROC

	PROCEDURE Load
		DO SET_SET
		
		GF_SQLEXEC("SELECT * FROM dbo.ss_tipi_dog","ss_tipi_dog")
		GF_SQLEXEC("SELECT * FROM dbo.ss_vrst_dog","ss_vrst_dog")
	ENDPROC

	PROCEDURE set_controls
		LOCAL lcSql, lcDom_valuta, laPar[1]
		DODEFAULT()
		WITH Thisform
			.tlbDogodki.btnUnlock.Enabled=.F.
			.tlbDogodki.btnSave.Enabled=(.tip_vnosne_maske<>0)	
			IF .tip_vnosne_maske <> 0 THEN  
				* Nastavitev objektov glede na polje zaklenjen
				IF NOT (GOBJ_Permissions.GetPermissionEx("SpecialServicesRecoveryReportEventUnlock", "EventType", ss_dogodek.id_tip_dog) < 1) THEN 
					.tlbDogodki.btnUnlock.Enabled = NOT ISNULL(ss_dogodek.zaklenjen)
				ENDIF
				
				.cboIdTipDog.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.cboIdVrsDog.Enabled=ISNULL(ss_dogodek.zaklenjen)
				* Pogodbe in partnerja na korekturah ni mogoèe spreminjati
				.txtIdPog.Enabled=ISNULL(ss_dogodek.zaklenjen) AND .tip_vnosne_maske=1
				.txtIdKupca.Enabled=ISNULL(ss_dogodek.zaklenjen) AND .tip_vnosne_maske=1
				.txtKontOseba.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtTelKo.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtGsmKo.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.cboObdeluje.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtSkladisce.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.cmdOpisDog.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.edtOpisDog.ReadOnly=!ISNULL(ss_dogodek.zaklenjen)
				.chkDetektiv.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkOdvzem.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkProdano.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkPrisPorav.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkStecaj.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkOdvetnik.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkOdpisTerj.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkTozba.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.chkUkraden.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtIdAgenc.Enabled=ISNULL(ss_dogodek.zaklenjen)
				* Polja je možno vnašati le, èe je vnešeno polje id_agenc
				.txtPredanoA.Enabled=ISNULL(ss_dogodek.zaklenjen) AND NOT (ISNULL(ss_dogodek.id_agenc) OR EMPTY(ss_dogodek.id_agenc))
				.txtVrnjenoA.Enabled=ISNULL(ss_dogodek.zaklenjen) AND NOT (ISNULL(ss_dogodek.id_agenc) OR EMPTY(ss_dogodek.id_agenc))
				.txtZakljucA.Enabled=ISNULL(ss_dogodek.zaklenjen) AND NOT (ISNULL(ss_dogodek.id_agenc) OR EMPTY(ss_dogodek.id_agenc))
				.txtRok.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtIzvedeno.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.edtToDo.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtPlacDogov.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtDatDogov.Enabled=ISNULL(ss_dogodek.zaklenjen)
				.txtDatDog.Enabled=ISNULL(ss_dogodek.zaklenjen)
			ELSE
				.edtOpombe.Enabled = .T.
				.edtOpombe.ReadOnly =.T.
				.cmdOpisDog.Enabled = .T.
				.edtOpisDog.Enabled = .T.
				.edtOpisdog.ReadOnly = .T.
			ENDIF
			IF .edtOpisdog.ReadOnly THEN
				.edtOpisDog.TabStop = .F.
				.edtOpisDog.ForeColor = RGB(128, 0, 64)
			ELSE
				.edtOpisDog.TabStop = .T.
				.edtOpisDog.ForeColor = RGB(0, 0, 0)
			ENDIF
			
			IF !GF_NULLOREMPTY(.id_ss_postopek) OR !GF_NULLOREMPTY(ss_dogodek.id_ss_postopek) THEN
				.txtIdKupca.Enabled = .F.
			ELSE
				.lblIdSsPostopek.Visible = .F.
				.txtIdSsPostopek.Visible = .F.	
			ENDIF
			
			* Nastavitev objektov, ki so povezani s pogodbo (vnos pogodbe ni obvezen)
			IF !GF_NULLOREMPTY(ss_dogodek.id_cont) THEN 
				IF GOBJ_Permissions.GetPermission("ActiveContractUpdate") = 2 THEN 
					.tlbDogodki.btnContractStatusChange.Enabled = .T. AND .tip_vnosne_maske <> 0
				ENDIF
				
				* Priprava podatkov o pogodbi
				TEXT TO lcSql NOSHOW 
					select 
						p.id_cont, p.id_pog, p.pred_naj, p.nacin_leas, p.status_akt, p.aneks, p.spl_pog, 
						p.id_kupca, par1.naz_kr_kup as kupca_naziv, 
						p.id_dob, par2.naz_kr_kup as dob_naziv, 
						p.status, s.naziv as statusi_naziv, 
						mg.naz_kr_kup as porok_naziv, 
					    case when vo.sifra = 'PO' then par1.kontakt else par1.naz_kr_kup end kontoseba, 
					    case when vo.sifra = 'PO' then par1.telefon_k else par1.telefon end konttel,  
					    par1.gsm 
					from 
						dbo.pogodba p
						inner join dbo.partner par1 on p.id_kupca = par1.id_kupca 
						inner join dbo.partner par2 on p.id_dob = par2.id_kupca 
						left join dbo.statusi s on p.status = s.status 
					    inner join dbo.vrst_ose vo on par1.vr_osebe = vo.vr_osebe
						outer apply (select top 1 naz_kr_kup from dbo.gfn_GetMainGuarrantor(p.id_cont)) mg 
					where p.id_cont = ?p1
				ENDTEXT 
				laPar[1] = ss_dogodek.id_cont
				IF GF_SQLEXEC_P(lcSql, @laPar, "pogodba") THEN
					.txtIdKupca.Enabled = .F.
					.txtNazIdKupca.Value = pogodba.kupca_naziv
					.txtIdPog.Value = pogodba.id_pog
					.txtPredNaj.Value = pogodba.pred_naj
					.txtNacinLeas.Value = pogodba.nacin_leas
					.txtStatusAkt.Value = pogodba.status_akt
					.txtAneks.Value = pogodba.aneks
					.txtStatus.Value = pogodba.statusi_naziv
					.txtSplPog.Value = pogodba.spl_pog
					.txtNazIdDob.Value = pogodba.dob_naziv
					
					IF ISNULL(ss_dogodek.ext_type) OR ISNULL(ss_dogodek.ext_id) OR !(ALLTRIM(ss_dogodek.ext_type) == "ODPOVED") THEN
						TEXT TO lcSql NOSHOW
							SELECT MAX(dat_izd_odp) AS dat_izd_odp
							  FROM dbo.odpoved
							 WHERE id_cont = {0}
							   AND izdana = 1
						ENDTEXT
						lcSql = STRTRAN(lcSql, "{0}", TRANSFORM(pogodba.id_cont))
					ELSE
						TEXT TO lcSql NOSHOW
							SELECT dat_izd_odp
							  FROM dbo.odpoved
							 WHERE id_odpoved = {0}
							   AND izdana = 1
						ENDTEXT
						lcSql = STRTRAN(lcSql, "{0}", ss_dogodek.ext_id)
					ENDIF
					.txtDatumOdp.Value = GF_SQLExecScalarNull(lcSql)
		
					* Priprava podatka o nazivu poroka
					.txtNazIdPoroka.Value = NVL(pogodba.porok_naziv, "")
								
					* Priprava podatkov o naslednjem obroku za pogodbo
					TEXT TO lcSql NOSHOW
						SELECT TOP 1 P.dat_zap, dbo.gfn_XChange('000', P.debit, P.id_tec, '{1}') AS debit
						  FROM dbo.planp P
						 INNER JOIN dbo.vrst_ter T ON P.id_terj = T.id_terj
						 WHERE P.id_cont = {0}
						   AND P.dat_zap >= '{1}'
						   AND T.sif_terj = 'LOBR'
						 ORDER BY P.dat_zap
					ENDTEXT
					lcSql = STRTRAN(lcSql, "{0}", TRANSFORM(pogodba.id_cont))
					lcSql = STRTRAN(lcSql, "{1}", DTOS(DATE()))
					IF GF_SQLEXEC(m.lcSql, "planp")
						.txtDatZap.Value = planp.dat_zap
						.txtDebit.Value = planp.debit
						USE IN planp
					ENDIF
					
					* Pri vnosu se predlaga kontaktna oseba in telefon
					IF .tip_vnosne_maske = 1 THEN 
						.txtKontOseba.Value = pogodba.kontoseba
						.txtTelKo.Value = pogodba.konttel
						.txtGsmKo.Value = pogodba.gsm
					ENDIF
		
					* Izraèun trenutnega dolga za partnerja
					.izracunaj_dolg_id_kupca = pogodba.id_kupca
					USE IN pogodba
				ENDIF
			ENDIF
			
			* Nastavitev objektov, ki so povezani s partnerjem (vnos partnerja je obvezen)
			IF GF_NULLOREMPTY(ss_dogodek.id_cont) AND !GF_NullOrEmpty(ss_dogodek.id_kupca) THEN 
				* Priprava podatkov o partnerju
				TEXT TO lcSql NOSHOW 
					select 
					    par.id_kupca, par.naz_kr_kup, 
					    case when vo.sifra = 'PO' then par.kontakt else par.naz_kr_kup end kontoseba, 
					    case when vo.sifra = 'PO' then par.telefon_k else par.telefon end konttel,  
					    par.gsm 
					from 
					    dbo.partner par
					    inner join dbo.vrst_ose vo on par.vr_osebe = vo.vr_osebe
					where par.id_kupca = ?p1
				ENDTEXT 
				laPar[1] = ss_dogodek.id_kupca
				IF GF_SQLEXEC_P(lcSql, @laPar, "_partner") THEN
					.txtNazIdKupca.Value = _partner.naz_kr_kup
					
					* Pri vnosu se predlaga kontaktna oseba in telefon
					IF .tip_vnosne_maske = 1 THEN 
						.txtKontOseba.Value = _partner.kontoseba
						.txtTelKo.Value = _partner.konttel
						.txtGsmKo.Value = _partner.gsm
					ENDIF	
					
					USE IN _partner
				ENDIF
					
				* Izraèun trenutnega dolga za partnerja
				.izracunaj_dolg_id_kupca = ss_dogodek.id_kupca
			ENDIF
			 	
			IF .tip_vnosne_maske=1 THEN 
				.cboIdTipDog.ListIndex= IIF(.cboIdTipDog.ListIndex=0, 1, .cboIdTipDog.ListIndex)
			ENDIF 
			
			.txtNazIdAgenc.Value=GF_LOOKUP("ss_agencije.opis",ss_dogodek.id_agenc,"ss_agencije.id_agenc")
			
				
			lcDom_valuta = GOBJ_Settings.GetVal("DOM_VALUTA")
			.txtid_val_debit.Value =  lcDom_valuta 
			.txtid_val_dolg_kupca.Value = lcDom_valuta 
			.txtid_val_dolg_dat_d.Value = lcDom_valuta 
			.txtid_val_dolg_danes_bzobr.Value = lcDom_valuta 
			.txtid_val_dog_zn.Value = lcDom_valuta 
			
			.txtid_val_debit.Enabled = .F.
			.txtid_val_dolg_kupca.Enabled = .F.
			.txtid_val_dolg_dat_d.Enabled = .F.
			.txtid_val_dolg_danes_bzobr.Enabled = .F.
			.txtid_val_dog_zn.Enabled = .F.
			
			SET FILTER TO id_tip_dog == ss_dogodek.id_tip_dog IN ss_vrst_dog
		ENDWITH 
	ENDPROC

	PROCEDURE set_permissions
		#INCLUDE ..\includes\locs.h
		
		LOCAL lcId_tip_dog
		
		lcId_tip_dog = ss_dogodek.id_tip_dog
		
		* preveri permission za form
		WITH Thisform
			* insert
			IF .tip_vnosne_maske = 1 THEN 
				IF GOBJ_Permissions.GetPermission("SpecialServicesRecoveryReportEventInsert") < 2 THEN
					pozor(STRTRAN(PERMISSION_DENIED, "{0}", "SpecialServicesRecoveryReportEventInsert"))
					RETURN .F.
				ENDIF
			ELSE
				* update
				IF .tip_vnosne_maske = 2 THEN
					IF GOBJ_Permissions.GetPermissionEx("SpecialServicesRecoveryReportEventUpdate", "EventType", lcId_tip_dog) < 2 THEN
						pozor(STRTRAN(PERMISSION_DENIED, "{0}", "SpecialServicesRecoveryReportEventUpdate"))
						RETURN .F.
					ENDIF
				ELSE
					* view		
					IF GOBJ_Permissions.GetPermission("SpecialServicesRecoveryReportEventViewOwn") < 1 AND GOBJ_Permissions.GetPermissionEx("SpecialServicesRecoveryReportEventViewAll", "EventType", lcId_tip_dog) < 1 THEN
							pozor(STRTRAN(PERMISSION_DENIED, "{0}", "SpecialServicesRecoveryReportEventViewOwn' ali 'SpecialServicesRecoveryReportEventViewAll"))
							RETURN .F.
					ENDIF
				ENDIF
			ENDIF
		ENDWITH 
		RETURN .T.
	ENDPROC

	PROCEDURE shrani
		#INCLUDE ..\includes\locs.h
		
		LOCAL lcXml, lcResult 
		
		WITH Thisform	
			IF .preveri_podatke(Thisform) THEN
				lcXml = '<insert_update_ss_dogodek xmlns="urn:gmi:nova:leasing">' + gcE
				lcXml = lcXml + '<ss_dogodek>' + gcE
				
				IF .tip_vnosne_maske = 2 THEN
					lcXml = lcXml + GF_CreateNode("id_dog", ss_dogodek.id_dog, "I", 1) + gcE
				ENDIF
				
				IF !GF_NULLOREMPTY(ss_dogodek.id_cont)
					lcXml = lcXml + GF_CreateNode("id_cont", ss_dogodek.id_cont, "I", 1) + gcE
				ENDIF 		
				lcXml = lcXml + GF_CreateNode("id_kupca", ss_dogodek.id_kupca, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("dat_vnosa", ss_dogodek.dat_vnosa, "T", 1) + gcE
				lcXml = lcXml + GF_CreateNode("vnesel", ss_dogodek.vnesel, "C", 1) + gcE 	  	
				IF !GF_NULLOREMPTY(ss_dogodek.rok)
					lcXml = lcXml + GF_CreateNode("rok", ss_dogodek.rok, "T", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.izvedeno)
					lcXml = lcXml + GF_CreateNode("izvedeno", ss_dogodek.izvedeno, "T", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.opis_dog)
					lcXml = lcXml + GF_CreateNode("opis_dog", ss_dogodek.opis_dog, "C", 1) + gcE
				ENDIF 
				lcXml = lcXml + GF_CreateNode("to_do", ss_dogodek.to_do, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("kont_oseba", ss_dogodek.kont_oseba, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("tel_ko", ss_dogodek.tel_ko, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("obdeluje", ss_dogodek.obdeluje, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("zakljucil", ss_dogodek.zakljucil, "C", 1) + gcE
				lcXml = lcXml + GF_CreateNode("opombe", ss_dogodek.opombe, "C", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("detektiv", ss_dogodek.detektiv, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("odvzem", ss_dogodek.odvzem, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("skladisce", ss_dogodek.skladisce, "C", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("prodano", ss_dogodek.prodano, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("pris_porav", ss_dogodek.pris_porav, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("stecaj", ss_dogodek.stecaj, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("odvetnik", ss_dogodek.odvetnik, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("tozba", ss_dogodek.tozba, "L", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("odpis_terj", ss_dogodek.odpis_terj, "L", 1) + gcE
				IF !GF_NULLOREMPTY(ss_dogodek.predano_a)
			    	lcXml = lcXml + GF_CreateNode("predano_a", ss_dogodek.predano_a, "T", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.vrnjeno_a)
			    	lcXml = lcXml + GF_CreateNode("vrnjeno_a", ss_dogodek.vrnjeno_a, "T", 1) + gcE
				ENDIF     	
				IF !GF_NULLOREMPTY(ss_dogodek.zakljuc_a)
			    	lcXml = lcXml + GF_CreateNode("zakljuc_a", ss_dogodek.zakljuc_a, "T", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.id_agenc)
			    	lcXml = lcXml + GF_CreateNode("id_agenc", ss_dogodek.id_agenc, "C", 1) + gcE
				ENDIF 
				lcXml = lcXml + GF_CreateNode("id_tip_dog", ss_dogodek.id_tip_dog, "C", 1) + gcE
			    lcXml = lcXml + GF_CreateNode("ukraden", ss_dogodek.ukraden, "L", 1) + gcE
			    
			    IF .tip_vnosne_maske = 2 THEN
			    	IF !GF_NULLOREMPTY(ss_dogodek.zaklenjen)
			    		lcXml = lcXml + GF_CreateNode("zaklenjen", ss_dogodek.zaklenjen, "T", 1) + gcE
			    	ELSE
			    		lcXml = lcXml + GF_CreateNode("zaklenjen", DATETIME(), "T", 1) + gcE 
					ENDIF 
			    ELSE 	
			    	lcXml = lcXml + GF_CreateNode("zaklenjen", DATETIME(), "T", 1) + gcE 
				ENDIF
					
			    lcXML = lcXML + GF_CreateNode("dolg_dat_d", ss_dogodek.dolg_dat_d, "N", 1) + gcE	
			    IF !GF_NULLOREMPTY(ss_dogodek.dat_dolg)
			    	lcXml = lcXml + GF_CreateNode("dat_dolg", ss_dogodek.dat_dolg, "T", 1) + gcE
			    ENDIF 
				lcXML = lcXML + GF_CreateNode("plac_dogov", ss_dogodek.plac_dogov, "N", 1) + gcE
				IF !GF_NULLOREMPTY(ss_dogodek.dat_dogov)
					lcXml = lcXml + GF_CreateNode("dat_dogov", ss_dogodek.dat_dogov, "T", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.dat_odzak)
					lcXml = lcXml + GF_CreateNode("dat_odzak", ss_dogodek.dat_odzak, "T", 1) + gcE
				ENDIF 
				lcXml = lcXml + GF_CreateNode("gsm_ko", ss_dogodek.gsm_ko, "C", 1) + gcE	
				IF !GF_NULLOREMPTY(ss_dogodek.ext_id)
					lcXml = lcXml + GF_CreateNode("ext_id", ss_dogodek.ext_id, "C", 1) + gcE	
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.ext_type)
					lcXml = lcXml + GF_CreateNode("ext_type", ss_dogodek.ext_type, "C", 1) + gcE	
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.id_vrs_dog)
					lcXml = lcXml + GF_CreateNode("id_vrs_dog", ss_dogodek.id_vrs_dog, "C", 1) + gcE
				ENDIF 
				IF !GF_NULLOREMPTY(ss_dogodek.id_ss_postopek)
					lcXml = lcXml + GF_CreateNode("id_ss_postopek", ss_dogodek.id_ss_postopek, "I", 1) + gcE
				ENDIF 
				lcXml = lcXml + GF_CreateNode("dat_poprave", DATETIME(), "T", 1) + gcE
				lcXml = lcXml + GF_CreateNode("datum_dogodka", ss_dogodek.datum_dogodka, "T", 1) + gcE
				lcXml = lcXml + '</ss_dogodek>' + gcE
				lcXml = lcXml + "</insert_update_ss_dogodek>"
					
				
				IF ! GF_ProcessXml(lcXml) THEN
					RETURN .f.
				ENDIF
				
				lcXml = GOBJ_Comm.GetResult()
				
				.id_field = VAL(GF_GetSingleNodeXml(lcXml, "id_dog"))
				
				IF .tip_vnosne_maske = 1 THEN
					obvesti(INFSAVED_LOC)
				ELSE
					obvesti(INFUPDATED_LOC)
				ENDIF
				
					
				.tip_vnosne_maske = 0
				.Release
			ELSE
				RETURN .F.
			ENDIF
			
				
		ENDWITH
		
		
	ENDPROC

	PROCEDURE cboIdTipDog.InteractiveChange
		Thisform.cboIdVrsDog.Requery
	ENDPROC

	PROCEDURE cboIdTipDog.LostFocus
		Thisform.cboIdVrsDog.Requery
		Thisform.cboIdVrsDog.Refresh
		IF Thisform.cboIdVrsDog.ListIndex = 0 THEN
			REPLACE id_vrs_dog WITH NULL IN ss_dogodek
		ENDIF
		
		GF_EXT_FUNC('IZTERJAVE_MASKA_TIP_DOGODKA_CHANGED')
		
		
	ENDPROC

	PROCEDURE chkDetektiv.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkOdpisTerj.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkOdvetnik.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkOdvzem.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkPrisPorav.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkProdano.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkStecaj.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkTozba.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE chkUkraden.KeyPress
		LPARAMETERS nKeyCode, nShiftAltCtrl
		IF nKeyCode=13 THEN 
			This.Value=NOT This.Value
		ENDIF
	ENDPROC

	PROCEDURE cmdOpisDog.Click
		LOCAL loResult
		
		DO FORM message_memo WITH ss_dogodek.opis_dog, "Opis dogodka", (Thisform.tip_vnosne_maske != 0) TO loResult
		IF TYPE("loResult") = "O" THEN
			IF loResult.Result = .T. THEN
				Thisform.edtOpisDog.Value = loResult.Text
			ENDIF
		ENDIF
		
	ENDPROC

	PROCEDURE cmdOpombe.Click
		LOCAL loResult
		
		DO FORM message_memo WITH ss_dogodek.opombe, "Opombe", (Thisform.tip_vnosne_maske != 0) TO loResult
		IF TYPE("loResult") = "O" THEN
			IF loResult.Result = .T. THEN
				Thisform.edtOpombe.Value = loResult.Text
			ENDIF
		ENDIF
		
	ENDPROC

	PROCEDURE tlbDogodki.btnContractStatusChange.Click
		LOCAL lcStatusNew
		
		IF EMPTY(ss_dogodek.id_cont) OR ISNULL(ss_dogodek.id_cont) THEN
			RETURN
		ENDIF
		
		IF Thisform.txtStatusAkt.Value = "Z" THEN
			IF !potrjeno("Pogodba je že zakljuèena! Ali vseeno želite spremeniti status na pogodbi?") THEN
				RETURN
			ENDIF
		ENDIF
		
		IF !INLIST(Thisform.txtStatusAkt.Value, "A", "Z") THEN
			pozor("Status je mogoèe spreminjati samo aktivnim in zakljuèenim pogodbam!")
			RETURN
		ENDIF
		
		DO FORM izterjave_pogodba_status_change WITH ss_dogodek.id_cont TO lcStatusNew
		IF TYPE("lcStatusNew") = "C" THEN
			Thisform.txtStatus.Value = GF_LOOKUP("statusi.naziv", lcStatusNew, "statusi.status")
		ENDIF
	ENDPROC

	PROCEDURE tlbDogodki.BTNEXIT.Click
		#INCLUDE ..\includes\locs.h
		
		thisform.EDTOPOMBE.Refresh
		
		
		SET STEP ON
		
		WITH Thisform
			IF .tip_vnosne_maske<>0  AND ISNULL(ss_dogodek.zaklenjen) THEN  
				
				* Preverimo ali je spremenjen podatek po izracunu
				GO TOP IN ss_dogodek
				   SELECT * FROM ss_dogodek;
			 	    UNION ;
				   SELECT * FROM _kopija_ss_dogodek;
			  		INTO CURSOR _ss_dogodek_sprememba
			
				IF ((RECCOUNT("_kopija_ss_dogodek") != RECCOUNT("_ss_dogodek_sprememba")) OR !(ALLTRIM(_kopija_ss_dogodek.opis_dog) == ALLTRIM(thisform.edtOpisDog.Value)) OR !(ALLTRIM(_kopija_ss_dogodek.to_do) == ALLTRIM(thisform.edtToDo.Value)) OR !(ALLTRIM(_kopija_ss_dogodek.opombe) == ALLTRIM(thisform.EDTOPOMBE.Value))) THEN
					IF potrjeno(SAVECHANGES_LOC)
						IF .shrani() THEN
							RETURN DODEFAULT()
						ENDIF 
					ENDIF
				ENDIF 
				USE IN _ss_dogodek_sprememba
			ENDIF
			
			IF .tip_vnosne_maske<>0  AND !ISNULL(ss_dogodek.zaklenjen) THEN  
				IF !(ALLTRIM(thisform.opombe_old) == ALLTRIM(thisform.EDTOPOMBE.Value)) THEN
					IF potrjeno(SAVECHANGES_LOC)
						IF .shrani() THEN
							RETURN DODEFAULT()
						ENDIF 
					ENDIF
				ENDIF 
			ENDIF 
		ENDWITH 
		RETURN DODEFAULT()
	ENDPROC

	PROCEDURE tlbDogodki.btnUnlock.Click
		* Odklene dogodek 
		SELECT ss_dogodek
		REPLACE ss_dogodek.zaklenjen WITH .NULL.
		LOCATE 
		
		SELECT * FROM ss_dogodek INTO CURSOR _kopija_ss_dogodek
		
		Thisform.set_controls 
	ENDPROC

	PROCEDURE tmrDolg.Timer
		IF Thisform.Izracunaj_dolg AND !GF_NullOrEmpty(Thisform.Izracunaj_dolg_id_kupca)THEN 
			Thisform.Izracunaj_dolg_all()
			Thisform.Izracunaj_dolg = .F.
			This.Interval = 0 && do not firing anymore
		ENDIF 
		
	ENDPROC

	PROCEDURE txtDatDog.Valid
		IF GF_NULLOREMPTY(this.Value) THEN
			SELECT ss_dogodek
			REPLACE ;
				datum_dogodka WITH dat_vnosa 
		ENDIF
	ENDPROC

	PROCEDURE txtIdAgenc.Valid
		LOCAL llVrni
		WITH Thisform
			llVrni=.T.
		
			.txtPredanoA.Enabled=NOT (ISNULL(This.Value) OR EMPTY(This.Value))
			.txtVrnjenoA.Enabled=NOT (ISNULL(This.Value) OR EMPTY(This.Value))
			.txtZakljucA.Enabled=NOT (ISNULL(This.Value) OR EMPTY(This.Value))
			
			IF ISNULL(This.Value) OR EMPTY(This.Value) THEN
				.txtNazIdAgenc.Value=""
				.txtPredanoA.Value=CTOD("")
				.txtVrnjenoA.Value=CTOD("")
				.txtZakljucA.Value=CTOD("")
				RETURN m.llVrni
			ENDIF 
			llVrni=GF_Obstoja("ss_agencije","id_agenc",This.Value,"id_agenc,opis","Agencija,Opis","ss_agencije","")
			IF m.llVrni=.T.
				REPLACE ss_dogodek.id_agenc WITH ss_agencije.id_agenc
				
				.txtNazIdAgenc.Value=ss_agencije.opis
				USE IN ss_agencije
			ENDIF
		ENDWITH
		RETURN m.llVrni
	ENDPROC

	PROCEDURE txtIdKupca.Valid
		LOCAL llVrni
		IF This.Other_data = This.Value THEN 
			RETURN .T.
		ENDIF 
		WITH Thisform
			llVrni = GF_ObstojaPartner(This.Value, "_partner", "")
			IF llVrni = .T. THEN 
				.txtIdKupca.Value = _partner.id_kupca
				
				.set_controls
				.izracunaj_dolg = .T.
				.tmrDolg.Interval = 1000 && sprozi izracun dolga cez 1 sekundo
			ENDIF
			IF USED("_partner") THEN 
				USE IN _partner
			ENDIF 
		ENDWITH
		RETURN llVrni
	ENDPROC

	PROCEDURE txtIdKupca.When
		This.Other_data = This.Value
	ENDPROC

	PROCEDURE txtIdPog.Valid
		LOCAL llVrni, lcFields, lcCaptions, lcPogoj, lcTitle, llEnabled
		
		llEnabled = GF_NULLOREMPTY(This.Value) AND ISNULL(ss_dogodek.zaklenjen) AND GF_NULLOREMPTY(Thisform.id_ss_postopek)
		* vrednost se ni spremenila
		llVrni = .T.
		IF ALLTRIM(This.Value) == ALLTRIM(This.Other_data) THEN 
			IF GF_NULLOREMPTY(This.Value) THEN 
				Thisform.txtIdKupca.Enabled = llEnabled
			ENDIF 
			
			RETURN llVrni
		ENDIF 
		WITH Thisform
			IF GF_NULLOREMPTY(This.Value) THEN
				.txtIdKupca.Enabled = llEnabled
				.txtPredNaj.Value = ""
				.txtNacinLeas.Value = ""
				.txtStatusAkt.Value = ""
				.txtAneks.Value = ""
				.txtStatus.Value = ""
				.txtSplPog.Value = ""
				.txtNazIdDob.Value = ""
				.txtDatumOdp.Value = CTOD("")
				.txtNazIdPoroka.Value = ""
				.txtDatZap.Value = CTOD("")
				.txtDebit.Value = 0
				.tlbDogodki.btnContractStatusChange.Enabled = .F.
				REPLACE id_cont WITH NULL IN ss_dogodek
				RETURN llVrni
			ENDIF 
			
			IF GF_NULLOREMPTY(.id_ss_postopek) THEN
				llVrni = GF_ObstojaPogodba(This.Value,"_pogodba","")
			ELSE
			    lcFields = "id_pog,pred_naj,id_kupca,naz_kr_kup,id_cont,status,nacin_leas,status_akt,sklic"
			    lcCaptions = "Šifra pogodbe,Predmet financiranja,Šif.part.,Naziv partnerja,Id_cont,Status,Tip financ.,Akt.,Sklic"  && Caption
			    lcPogoj = "id_ss_postopek = " + TRANSFORM(.id_ss_postopek)
			    lcTitle = "Izberi pogodbo"  && Caption
				llVrni = GF_Obstoja("gv_ObstojaSsTPogodba", "id_pog", This.Value, lcFields, lcCaptions, "_pogodba", lcPogoj, 1, lcTitle)
			ENDIF
			IF llVrni = .T. THEN
				REPLACE id_cont WITH _pogodba.id_cont IN ss_dogodek
				
				.txtIdPog.Value = _pogodba.id_pog
				.txtIdKupca.Value = _pogodba.id_kupca
				
				.set_controls
				.izracunaj_dolg = .T.
				.tmrDolg.Interval = 1000 && sprozi izracun dolga cez 1 sekundo
			ENDIF 
			IF USED("_pogodba") THEN 
				USE IN _pogodba
			ENDIF 
		ENDWITH
		RETURN llVrni
	ENDPROC

	PROCEDURE txtIdPog.When
		This.Other_data = This.Value
	ENDPROC

	PROCEDURE txtPlacDogov.Valid
		WITH Thisform
			* Èe je vnešen dogovorjeni znesek plaèila, se predlaga Dogov.dat.plaè iz polja rok
			IF NOT EMPTY(This.Value) AND (EMPTY(.txtDatDogov.Value) OR ISNULL(.txtDatDogov.Value)) THEN
				.txtDatDogov.Value=.txtRok.Value
			ENDIF
		ENDWITH
		RETURN .T.
	ENDPROC

	PROCEDURE txtSkladisce.Valid
		GF_EXT_FUNC("IZTERJAVE_MASKA_SKLADISCE_VALID")
	ENDPROC

ENDDEFINE
