begin transaction
delete from regije
INSERT INTO regije VALUES ('000','DUMMY')
INSERT INTO regije VALUES ('001','ZAGREBAÈKA')
INSERT INTO regije VALUES ('002','KRAPINSKO ZAGORSKA')
INSERT INTO regije VALUES ('003','SISAÈKO MOSLAVAÈKA')
INSERT INTO regije VALUES ('004','KARLOVAÈKA')
INSERT INTO regije VALUES ('005','VARAŽDINSKA')
INSERT INTO regije VALUES ('006','KOPRIVNIÈKO KRIŽEVAÈKA')
INSERT INTO regije VALUES ('007','BJELOVARSKO BILOGORSKA')
INSERT INTO regije VALUES ('008','PRIMORSKO GORANSKA')
INSERT INTO regije VALUES ('009','LIÈKO SENJSKA')
INSERT INTO regije VALUES ('010','VIROVITIÈKO PODRAVSKA')
INSERT INTO regije VALUES ('011','POŽEŠKO SLAVONSKA')
INSERT INTO regije VALUES ('012','BRODSKO POSAVSKA')
INSERT INTO regije VALUES ('013','ZADARSKA')
INSERT INTO regije VALUES ('014','OSJEÈKO BARANJSKA')
INSERT INTO regije VALUES ('015','ŠIBENSKO KNINSKA')
INSERT INTO regije VALUES ('016','VUKOVARSKO SRIJEMSKA')
INSERT INTO regije VALUES ('017','SPLITSKO DALMATINSKA')
INSERT INTO regije VALUES ('018','ISTARSKA')
INSERT INTO regije VALUES ('019','DUBROVAÈKO NERETVANSKA')
INSERT INTO regije VALUES ('022','GRAD ZAGREB')
INSERT INTO regije VALUES ('020','MEÐIMURSKA')
INSERT INTO regije VALUES ('999','STRANA')

SELECT [ID_REG],[NAZIV] FROM [nova_rlc].[dbo].[REGIJE]
--rollback