begin tran
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	228176
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	267213
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383094
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	332782
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	375662
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414976
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414979
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	284902
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	302666
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	314290
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	370833
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	396564
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383090
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	332823
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	399774
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383095
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	356056
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	386687
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	418882
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408229
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	384419
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383100
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	353064
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383091
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	425573
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	426330
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408061
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	372429
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383882
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383089
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	386688
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	287560
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	411497
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	394451
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	423023
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	438821
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	356057
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	303619
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	308400
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383093
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408062
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	410091
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	423903
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	450612
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	411229
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	388336
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408507
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	430271
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383098
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	423899
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460106
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	461868
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	419804
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408506
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383096
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	405651
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	419803
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	346848
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460110
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	461854
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	488171
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460105
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460509
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	458059
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	488118
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414796
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	518925
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	464909
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460810
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414982
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517051
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	461679
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	248814
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	451931
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	488143
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	509079
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	509091
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414975
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460272
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	477381
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	483565
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	487717
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	430285
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	418443
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	433879
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	434550
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	392271
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	412873
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383097
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460515
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460269
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	467720
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408226
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	477384
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460516
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414822
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	461687
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460268
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	467718
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	519116
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	248812
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	452379
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	345196
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	490408
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	513054
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	328920
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	472073
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	516177
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	479543
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460512
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	346849
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	430273
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	490409
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383092
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	383099
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	459406
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	521331
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	410090
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	521163
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	408228
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	414819
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	421825
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	423920
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	443879
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	407080
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	421826
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	482069
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	440384
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517004
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	443703
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	453887
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517095
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517101
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	483272
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	512376
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	526962
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	396160
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	405496
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	423919
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	518938
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	520448
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	450543
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460096
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	482767
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	421311
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	460276
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	478019
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	521332
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	521164
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	523982
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	519117
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	516990
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	521647
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517019
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	438820
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	487722
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	515836
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	516991
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	482777
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	520406
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	517027
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	516868
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	394444
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	523968
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	525562
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	516176
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	526757
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	520589
UPDATE dokument SET status_akt='N', popravil='g_system', dat_poprave=getdate(),dat_zakl='20130312' where status_akt!='N' and id_dokum=	508642
--commit

select status_akt, dat_poprave,popravil,dat_zakl,* from dokument
where popravil='g_system' and dat_poprave>'20130311'
order by id_dokum