
--backup
INSERT INTO dbo.STATUS_PLACILA(ID_PLAC_IZH,DATUM,IZ_STATUS,V_STATUS,KDO,V_IMENU,OPOMBA) VALUES(10743,'May  7 2013  9:36AM','I','I','mirandab',NULL,NULL)
INSERT INTO dbo.STATUS_PLACILA(ID_PLAC_IZH,DATUM,IZ_STATUS,V_STATUS,KDO,V_IMENU,OPOMBA) VALUES(10743,'May  7 2013  9:38AM','I','V','mirandab',NULL,NULL)
INSERT INTO dbo.STATUS_PLACILA(ID_PLAC_IZH,DATUM,IZ_STATUS,V_STATUS,KDO,V_IMENU,OPOMBA) VALUES(10743,'May  7 2013  9:43AM','V','E','dunjal',NULL,NULL)
INSERT INTO dbo.STATUS_PLACILA(ID_PLAC_IZH,DATUM,IZ_STATUS,V_STATUS,KDO,V_IMENU,OPOMBA) VALUES(10743,'May  7 2013 10:05AM','E','A','ljiljanas',3,NULL)
INSERT INTO dbo.STATUS_PLACILA(ID_PLAC_IZH,DATUM,IZ_STATUS,V_STATUS,KDO,V_IMENU,OPOMBA) VALUES(10743,'May  7 2013 11:04AM','A','P','natalijas',NULL,NULL)


begin tran
SELECT * FROM STATUS_PLACILA WHERE ID_PLAC_IZH = 10743
DELETE FROM STATUS_PLACILA WHERE ID_PLAC_IZH = 10743 -- da bi se mogao obrisati zapis

SELECT * FROM PLAC_IZH WHERE ID_PLAC_IZH = 10743
UPDATE PLAC_IZH SET STATUS_PLACILA = 'C' WHERE ID_PLAC_IZH = 10743 -- ili STATUS_PLACILA = 'I'
--commit
--rollback

--10743