DECLARE @id varchar(100)
SET @id = 55980 --Plovilo 55980, osobno vozilo 56149 

SELECT ZAP_REG.ID_ZAPO, ZAP_REG.ID_CONT
	, CONVERT(varchar(10), ZAP_REG.DAT_PREV, 104) AS DAT_PREV
	, ZAP_REG.VRSTA, ISNULL(Y.NAZIV, ZAP_REG.VRSTA) as VRSTE_OPR_REG_NAZIV 
	, ZAP_REG.ZNAMKA, ISNULL(X.NAZIV, ZAP_REG.ZNAMKA) as ZNAMKA_NAZIV
	, ZAP_REG.TIP, ZAP_REG.ST_SAS, ZAP_REG.ST_MOT, ZAP_REG.LET_PRO,
  ZAP_REG.BARVA, ZAP_REG.REG_STEV, ZAP_REG.ST_PROMD, ZAP_REG.DAT_PD,
  ZAP_REG.VELJ_PD, ZAP_REG.OPIS, ZAP_REG.SPL_POG, ZAP_REG.ID_KUPCA,
  ZAP_REG.ID_DOB, ZAP_REG.PS_KW, ZAP_REG.KUBIK, ZAP_REG.VNESEL,
  ZAP_REG.ST_KLJUC, ZAP_REG.IDENTICAR, ZAP_REG.PROIZV_ST, ZAP_REG.KOMENTAR,
  ZAP_REG.ST_SEDEZEV, ZAP_REG.NOSILNOST, ZAP_REG.MESTO_UPO,
  ZAP_REG.ST_KNJ_VOZILA, ZAP_REG.STOPNJA_AM, ZAP_REG.ST_FAKTURE,
  ZAP_REG.DAT_FAKT, ZAP_REG.ALI_V_OS, ZAP_REG.NABAV_VRED, ZAP_REG.PRENOS,
  ZAP_REG.TEZA_PRAZ, ZAP_REG.PDAT_PREV, ZAP_REG.SYS_TS, ZAP_REG.KILOMETRI,
  ZAP_REG.DAT_1UPOR, ZAP_REG.RABLJENO, ZAP_REG.PRODANO
FROM dbo.ZAP_REG
LEFT JOIN dbo.znamke as X ON ZAP_REG.znamka = X.id_znamke
LEFT JOIN dbo.vrste_opr_reg as Y ON ZAP_REG.vrsta = Y.id_vrste
WHERE ZAP_REG.ID_CONT = @id
ORDER BY ZAP_REG.ID_ZAPO Desc
