-- skripta za podešavanje na produkciju
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','SU20',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','SU25',1,1,'001',8)

-- skripta za podešavanje na test
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S20',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S25',1,1,'001',8)


--ostalo 
select st_dok_dob, prenos, * from gl_subvenc

--UPDATE gl_subvenc SET st_dok_dob = '', prenos = NULL WHERE id_gl_subvenc = 34
SELECT * FROM [dbo].[GL_SUBV_CHANNELS] 

--sp_helptext gsp_gl_generatesubsidyinvoices 

select * from GL_SUBV_SIF where id_dav_st = '00'

/*
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S00',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S30',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S40',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S50',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S60',1,1,'001',8)
INSERT INTO dbo.gl_subv_sif(NACIN_LEAS,ID_KUPCA,IZRACUN,PROC_PROD,PROC_DOB,OPISDOK,ID_DAV_ST,ID_STRM,KONTO,PROTIKONTO,RAZ_PKONTO,PKD,TIP_KNJIGE,VR_PROM,OUT_RK_ANA,KOSOV_1,GLAVA,REP,KATEGORIJA,id_channel,raz_activate,id_obd,DNI_ZAP) VALUES('F1','','select dbo.gfn_Xchange(''000'', p.rabat, p.id_tec, pl.datum) from dbo.pogodba p cross apply (select min(datum) as datum from dbo.plac_izh pl where id_cont = p.id_cont group by id_cont) pl where p.id_cont = @p_id_cont',0.00,100.00,'Naknada za ekskluz.uvjeta','25','0010','150001','293019','770030','260201','IRAC','1',1,1,'','','S70',1,1,'001',8)
*/