Osnovica
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum), Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum))}
--novo
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum), Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum))}


%PDV
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)))}
--novo
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)))}


Ukupno s PDV
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)))}
--novo
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100)))}


Ukupno za plaćanje 
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", ((NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100))+NEZAPADLO.robresti_Sum), Format("{0:N2}", ((NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.dodatne_ter+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100))+NEZAPADLO.robresti_Sum))}
--novo
{IIF(cont4prov.tip_leas == "OL", Format("{0:N2}", ((NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100))+NEZAPADLO.robresti_Sum), Format("{0:N2}", ((NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+cont4prov.se_varsc+cont4prov.str_odv_s_pdv+cont4prov.str_man+(((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) + ((cont4prov.se_varsc + NEZAPADLO.VOPC_disk_vred_Sum)*(cont4prov.str_proc / 100)) * (cont4prov.xdavek1 / 100))-NEZAPADLO.robresti_Sum)*(cont4prov.pon_davek/100))+NEZAPADLO.robresti_Sum))}