str_sod
str_vrac_kas

104
--staro
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum),Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))-NEZAPADLO.robresti_Sum))} 
--novo
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum),Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))-NEZAPADLO.robresti_Sum))}

107
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}
--novo
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}

191
( od osnove {IIF(cont4prov.PDV_u_rati!=1,NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum,NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))-NEZAPADLO.robresti_Sum)} {cont4prov.id_val.Trim()} )
--novo
( od osnove {IIF(cont4prov.PDV_u_rati!=1,NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum,NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))-NEZAPADLO.robresti_Sum)} {cont4prov.id_val.Trim()} )

110
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}
--novo
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}

116
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum))}
--novo
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum))}

125
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum+cont4prov.dodatne_ter_bruto), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum))}
--novo
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum+cont4prov.dodatne_ter_bruto), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum))}

168
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))),Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))))}
--novo
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))),Format("{0:N2}", NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))))}

172
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}
--novo
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)), Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)))}

174
( od osnove {IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}",NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))),Format("{0:N2}",NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))))} {cont4prov.id_val.Trim()} )
--novo
( od osnove {IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}",NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))),Format("{0:N2}",NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.pog_davek/100))))} {cont4prov.id_val.Trim()} )

177
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)))+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))*(cont4prov.id_dav_st/100)))}
--novo
{IIF(cont4prov.PDV_u_rati==1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)))+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))*(cont4prov.id_dav_st/100)))}

184
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum))}
--novo
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)+(NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100))-NEZAPADLO.robresti_Sum)*(cont4prov.id_dav_st/100)+NEZAPADLO.robresti_Sum))}

205
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_sod+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))*(cont4prov.id_dav_st/100)+OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum))}
--novo
{IIF(cont4prov.PDV_u_rati!=1,Format("{0:N2}", OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum),Format("{0:N2}", (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))+ (NEZAPADLO.VOPC_disk_vred_Sum+OfferResultSum.varscina2_Sum+cont4prov.str_odv_s_pdv+cont4prov.str_man_s_pdv+cont4prov.dodatne_ter_bruto+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100))+((OfferResultSum.varscina2_Sum + NEZAPADLO.VOPC_disk_vred_Sum) * (cont4prov.str_proc/100)*(cont4prov.id_dav_st/100)))*(cont4prov.id_dav_st/100)+OfferResultSum.zam_obr_Sum+ZE_ZAPADLO.net_val_Sum))}
