173:     <data_field name="contact_desc" type="string" title="Ime i prezime kontakt osobe" description="Ime i prezime kontakt osobe" display_to_user="true" display_group="1. Osnovni podaci o društvu/fizičkoj osobi" />
196:     <data_field name="related_po_manage_desc1" type="string" title="1. Tvrtka društva" description="1. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
249:     <data_field name="related_po_manage_desc2" type="string" title="2. Tvrtka društva" description="2. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
302:     <data_field name="related_po_manage_desc3" type="string" title="3. Tvrtka društva" description="3. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
355:     <data_field name="related_po_manage_desc4" type="string" title="4. Tvrtka društva" description="4. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
409:     <data_field name="related_fo_manage_desc1" type="string" title="1. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="1. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
468:     <data_field name="related_fo_manage_desc2" type="string" title="2. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="2. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
527:     <data_field name="related_fo_manage_desc3" type="string" title="3. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="3. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
586:     <data_field name="related_fo_manage_desc4" type="string" title="4. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="4. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
651:     <data_field name="management_desc1" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
680:     <data_field name="management_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
709:     <data_field name="management_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
745:     <data_field name="procurator_desc1" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
779:     <data_field name="procurator_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
813:     <data_field name="procurator_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
875:     <data_field name="consolidation_desc1" type="string" description="1. Pravna osoba" title="1. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
901:     <data_field name="consolidation_desc2" type="string" description="2. Pravna osoba" title="2. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
927:     <data_field name="consolidation_desc3" type="string" description="3. Pravna osoba" title="3. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
954:     <data_field name="assignee_desc" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1016:     <data_field name="assignee_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1077:     <data_field name="assignee_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1137:     <data_field name="assignee_desc4" type="string" title="4. Ime i prezime" description="4. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
/*
1246:     <data_field name="global_customer_desc" type="string" description="Global customer name for shared evaluator" title="Global customer name for shared evaluator" display_to_user="false" />
1247:     <data_field name="global_customer_desc_doubtful" type="enum" description="Global customer name doubtful for shared evaluator" title="Global customer name doubtful for shared evaluator" display_to_user="false">
1253:     <data_field name="global_desc_doubtful" type="string" display_to_user="false" description="global description doubtful" title="global description doubtful" />
1292:     <data_field name="global_instance_description" type="string" title="global instance description" description="global instance description" display_to_user="false" />
1294:     <data_field name="global_fo_check_step_desc" type="string" title="default message for fo_check step" description="default message for fo_check step" display_to_user="false" />
1307:     <data_field name="related_fo_manage_desc1_is_pio" type="boolean" title="1. osoba koja upravlja društvom je PEP" description="1. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1308:     <data_field name="related_fo_manage_desc1_child_process_id" type="int" title="Id upitnika za 1. osobu koja upravlja društvom" description="Id upitnika za 1. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1309:     <data_field name="related_fo_manage_desc2_is_pio" type="boolean" title="2. osoba koja upravlja društvom je PEP" description="2. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1310:     <data_field name="related_fo_manage_desc2_child_process_id" type="int" title="Id upitnika za 2. osobu koja upravlja društvom" description="Id upitnika za 2. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1311:     <data_field name="related_fo_manage_desc3_is_pio" type="boolean" title="3. osoba koja upravlja društvom je PEP" description="3. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1312:     <data_field name="related_fo_manage_desc3_child_process_id" type="int" title="Id upitnika za 3. osobu koja upravlja društvom" description="Id upitnika za 3. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1313:     <data_field name="related_fo_manage_desc4_is_pio" type="boolean" title="4. osoba koja upravlja društvom je PEP" description="4. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1314:     <data_field name="related_fo_manage_desc4_child_process_id" type="int" title="Id upitnika za 4. osobu koja upravlja društvom" description="Id upitnika za 4. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1316:     <data_field name="management_desc1_is_pio" type="boolean" title="1. član uprave je PIO" description="1. član uprave je PIO" display_to_user="true" display_group="2.3 Uprava društva" />
1317:     <data_field name="managment_desc1_child_process_id" type="int" title="Id upitnika za 1. člana uprave društva" description="Id upitnika za 1. člana uprave društva" display_to_user="true" display_group="2.3 Uprava društva" />
1318:     <data_field name="management_desc2_is_pio" type="boolean" title="2. član uprave je PIO" description="2. član uprave je PIO" display_to_user="true" display_group="2.3 Uprava društva" />
1319:     <data_field name="managment_desc2_child_process_id" type="int" title="Id upitnika za 2. člana uprave društva" description="Id upitnika za 2. člana uprave društva" display_to_user="true" display_group="2.3 Uprava društva" />
1320:     <data_field name="management_desc3_is_pio" type="boolean" title="3. član uprave je PIO" description="3. član uprave je PIO" display_to_user="false" display_group="2.3 Uprava društva" />
1321:     <data_field name="managment_desc3_child_process_id" type="int" title="Id upitnika za 3. člana uprave društva" description="Id upitnika za 3. člana uprave društva" display_to_user="false" display_group="2.3 Uprava društva" />
1323:     <data_field name="procurator_desc1_is_pio" type="boolean" title="1. prokurist je PIO" description="1. prokurist je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1324:     <data_field name="procurator_desc1_child_process_id" type="int" title="Id upitnika za 1. prokurista društva" description="Id upitnika za 1. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1325:     <data_field name="procurator_desc2_is_pio" type="boolean" title="2. prokurist je PIO" description="2. član nadzornog odbora je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1326:     <data_field name="procurator_desc2_child_process_id" type="int" title="Id upitnika za 2. prokurista društva" description="Id upitnika za 2. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1327:     <data_field name="procurator_desc3_is_pio" type="boolean" title="3. prokurist je PIO" description="3. prokurist je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1328:     <data_field name="procurator_desc3_child_process_id" type="int" title="Id upitnika za 3. prokurista društva" description="Id upitnika za 3. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1330:     <data_field name="assignee_desc_is_pio" type="boolean" title="1. Zastupnik/punomoćenik društva je PIO" description="1. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1331:     <data_field name="assignee_desc_child_process_id" type="int" title="1. Id upitnika za zastupnika/punomoćenika društva" description="1. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1332:     <data_field name="assignee_desc_is_pio2" type="boolean" title="2. Zastupnik/punomoćenik društva je PIO" description="2. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1333:     <data_field name="assignee_desc_child_process_id2" type="int" title="2. Id upitnika za zastupnika/punomoćenika društva" description="2. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1334:     <data_field name="assignee_desc_is_pio3" type="boolean" title="3. Zastupnik/punomoćenik društva je PIO" description="3. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1335:     <data_field name="assignee_desc_child_process_id3" type="int" title="3. Id upitnika za zastupnika/punomoćenika društva" description="3. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1336:     <data_field name="assignee_desc_is_pio4" type="boolean" title="4. Zastupnik/punomoćenik društva je PIO" description="4. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1337:     <data_field name="assignee_desc_child_process_id4" type="int" title="4. Id upitnika za zastupnika/punomoćenika društva" description="4. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />*/



/* BACKUP
SVI  _DESC
  55:     <data_field name="customer_desc" type="string" title="  Naziv/ime i prezime (primatelja leasing)" description="  Naziv/ime i prezime (primatelja leasing)" display_to_user="true" display_group="1. Osnovni podaci o društvu/fizičkoj osobi" />
  56:     <data_field name="customer_desc_doubtful" type="enum" description="Primatelj leasinga je na popisu sumnjivih osoba?" title="Primatelj leasinga je na popisu sumnjivih osoba?" display_to_user="true" display_group="1. Osnovni podaci o društvu/fizičkoj osobi">
 173:     <data_field name="contact_desc" type="string" title="Ime i prezime kontakt osobe" description="Ime i prezime kontakt osobe" display_to_user="true" display_group="1. Osnovni podaci o društvu/fizičkoj osobi" />
 174:     <data_field name="contact_desc_doubtful" type="enum" description="Kontakt osoba je na popisu sumnjivih osoba?" title="Kontakt osoba je na popisu sumnjivih osoba?" display_to_user="true" display_group="1. Osnovni podaci o društvu/fizičkoj osobi">
 196:     <data_field name="related_po_manage_desc1" type="string" title="1. Tvrtka društva" description="1. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
 197:     <data_field name="related_po_manage_desc1_doubtful" type="enum" description="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe">
 249:     <data_field name="related_po_manage_desc2" type="string" title="2. Tvrtka društva" description="2. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
 250:     <data_field name="related_po_manage_desc2_doubtful" type="enum" description="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe">
 302:     <data_field name="related_po_manage_desc3" type="string" title="3. Tvrtka društva" description="3. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
 303:     <data_field name="related_po_manage_desc3_doubtful" type="enum" description="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe">
 355:     <data_field name="related_po_manage_desc4" type="string" title="4. Tvrtka društva" description="4. Tvrtka društva" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe" />
 356:     <data_field name="related_po_manage_desc4_doubtful" type="enum" description="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Pravna osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.1 Vlasnička struktura - pravne osobe">
 409:     <data_field name="related_fo_manage_desc1" type="string" title="1. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="1. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
 413:     <data_field name="related_fo_manage_desc1_doubtful" type="enum" description="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe">
 468:     <data_field name="related_fo_manage_desc2" type="string" title="2. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="2. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
 472:     <data_field name="related_fo_manage_desc2_doubtful" type="enum" description="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe">
 527:     <data_field name="related_fo_manage_desc3" type="string" title="3. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="3. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
 531:     <data_field name="related_fo_manage_desc3_doubtful" type="enum" description="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe">
 586:     <data_field name="related_fo_manage_desc4" type="string" title="4. Ime i prezime (Vlasnička struktura - fizičke osobe)" description="4. Ime i prezime (Vlasnička struktura - fizičke osobe)" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
 590:     <data_field name="related_fo_manage_desc4_doubtful" type="enum" description="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" title="Fizička osoba koja upravlja društvom je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe">
 651:     <data_field name="management_desc1" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
 655:     <data_field name="management_desc1_doubtful" type="enum" description="Član uprave je na popisu sumnjivih osoba?" title="Član uprave je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.3 Uprava društva">
 680:     <data_field name="management_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
 684:     <data_field name="management_desc2_doubtful" type="enum" description="Član uprave je na popisu sumnjivih osoba?" title="Član uprave je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.3 Uprava društva">
 709:     <data_field name="management_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="2.3 Uprava društva" />
 713:     <data_field name="management_desc3_doubtful" type="enum" description="Član uprave je na popisu sumnjivih osoba?" title="Član uprave je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.3 Uprava društva">
 745:     <data_field name="procurator_desc1" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
 749:     <data_field name="procurator_desc1_doubtful" type="enum" description="Prokurist društva je na popisu sumnjivih osoba?" title="Prokurist društva je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.4 Prokuristi društva">
 779:     <data_field name="procurator_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
 783:     <data_field name="procurator_desc2_doubtful" type="enum" description="Prokurist društva je na popisu sumnjivih osoba?" title="Prokurist društva je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.4 Prokuristi društva">
 813:     <data_field name="procurator_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="2.4 Prokuristi društva" />
 817:     <data_field name="procurator_desc3_doubtful" type="enum" description="Prokurist društva je na popisu sumnjivih osoba?" title="Prokurist društva je na popisu sumnjivih osoba?" display_to_user="true" display_group="2.4 Prokuristi društva">
 875:     <data_field name="consolidation_desc1" type="string" description="1. Pravna osoba" title="1. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
 876:     <data_field name="consolidation_desc1_doubtful" type="enum" description="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" title="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" display_to_user="true" display_group="3.2. Konsolidacija">
 901:     <data_field name="consolidation_desc2" type="string" description="2. Pravna osoba" title="2. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
 902:     <data_field name="consolidation_desc2_doubtful" type="enum" description="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" title="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" display_to_user="true" display_group="3.2. Konsolidacija">
 927:     <data_field name="consolidation_desc3" type="string" description="3. Pravna osoba" title="3. Pravna osoba" display_to_user="true" display_group="3.2. Konsolidacija" />
 928:     <data_field name="consolidation_desc3_doubtful" type="enum" description="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" title="Pravna osoba uključena u konsolidaciju je na popisu sumnjivih osoba?" display_to_user="true" display_group="3.2. Konsolidacija">
 954:     <data_field name="assignee_desc" type="string" title="1. Ime i prezime" description="1. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
 957:     <data_field name="assignee_desc_doubtful" type="enum" description="1. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" title="1. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik">
1016:     <data_field name="assignee_desc2" type="string" title="2. Ime i prezime" description="2. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1019:     <data_field name="assignee_desc_doubtful2" type="enum" description="2. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" title="2. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik">
1077:     <data_field name="assignee_desc3" type="string" title="3. Ime i prezime" description="3. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1080:     <data_field name="assignee_desc_doubtful3" type="enum" description="3. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" title="3. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik">
1137:     <data_field name="assignee_desc4" type="string" title="4. Ime i prezime" description="4. Ime i prezime" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1140:     <data_field name="assignee_desc_doubtful4" type="enum" description="4. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" title="4. Ime i prezime zakonskog zastupnika/punomoćenika je na popisu adresa sumnjivih osoba?" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik">
1246:     <data_field name="global_customer_desc" type="string" description="Global customer name for shared evaluator" title="Global customer name for shared evaluator" display_to_user="false" />
1247:     <data_field name="global_customer_desc_doubtful" type="enum" description="Global customer name doubtful for shared evaluator" title="Global customer name doubtful for shared evaluator" display_to_user="false">
1253:     <data_field name="global_desc_doubtful" type="string" display_to_user="false" description="global description doubtful" title="global description doubtful" />
1292:     <data_field name="global_instance_description" type="string" title="global instance description" description="global instance description" display_to_user="false" />
1294:     <data_field name="global_fo_check_step_desc" type="string" title="default message for fo_check step" description="default message for fo_check step" display_to_user="false" />
1307:     <data_field name="related_fo_manage_desc1_is_pio" type="boolean" title="1. osoba koja upravlja društvom je PEP" description="1. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1308:     <data_field name="related_fo_manage_desc1_child_process_id" type="int" title="Id upitnika za 1. osobu koja upravlja društvom" description="Id upitnika za 1. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1309:     <data_field name="related_fo_manage_desc2_is_pio" type="boolean" title="2. osoba koja upravlja društvom je PEP" description="2. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1310:     <data_field name="related_fo_manage_desc2_child_process_id" type="int" title="Id upitnika za 2. osobu koja upravlja društvom" description="Id upitnika za 2. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1311:     <data_field name="related_fo_manage_desc3_is_pio" type="boolean" title="3. osoba koja upravlja društvom je PEP" description="3. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1312:     <data_field name="related_fo_manage_desc3_child_process_id" type="int" title="Id upitnika za 3. osobu koja upravlja društvom" description="Id upitnika za 3. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1313:     <data_field name="related_fo_manage_desc4_is_pio" type="boolean" title="4. osoba koja upravlja društvom je PEP" description="4. osoba koja upravlja društvom je PEP" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1314:     <data_field name="related_fo_manage_desc4_child_process_id" type="int" title="Id upitnika za 4. osobu koja upravlja društvom" description="Id upitnika za 4. osobu koja upravlja društvom" display_to_user="true" display_group="2.2 Vlasnička struktura - fizičke osobe" />
1316:     <data_field name="management_desc1_is_pio" type="boolean" title="1. član uprave je PIO" description="1. član uprave je PIO" display_to_user="true" display_group="2.3 Uprava društva" />
1317:     <data_field name="managment_desc1_child_process_id" type="int" title="Id upitnika za 1. člana uprave društva" description="Id upitnika za 1. člana uprave društva" display_to_user="true" display_group="2.3 Uprava društva" />
1318:     <data_field name="management_desc2_is_pio" type="boolean" title="2. član uprave je PIO" description="2. član uprave je PIO" display_to_user="true" display_group="2.3 Uprava društva" />
1319:     <data_field name="managment_desc2_child_process_id" type="int" title="Id upitnika za 2. člana uprave društva" description="Id upitnika za 2. člana uprave društva" display_to_user="true" display_group="2.3 Uprava društva" />
1320:     <data_field name="management_desc3_is_pio" type="boolean" title="3. član uprave je PIO" description="3. član uprave je PIO" display_to_user="false" display_group="2.3 Uprava društva" />
1321:     <data_field name="managment_desc3_child_process_id" type="int" title="Id upitnika za 3. člana uprave društva" description="Id upitnika za 3. člana uprave društva" display_to_user="false" display_group="2.3 Uprava društva" />
1323:     <data_field name="procurator_desc1_is_pio" type="boolean" title="1. prokurist je PIO" description="1. prokurist je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1324:     <data_field name="procurator_desc1_child_process_id" type="int" title="Id upitnika za 1. prokurista društva" description="Id upitnika za 1. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1325:     <data_field name="procurator_desc2_is_pio" type="boolean" title="2. prokurist je PIO" description="2. član nadzornog odbora je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1326:     <data_field name="procurator_desc2_child_process_id" type="int" title="Id upitnika za 2. prokurista društva" description="Id upitnika za 2. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1327:     <data_field name="procurator_desc3_is_pio" type="boolean" title="3. prokurist je PIO" description="3. prokurist je PIO" display_to_user="true" display_group="2.4 Prokuristi društva" />
1328:     <data_field name="procurator_desc3_child_process_id" type="int" title="Id upitnika za 3. prokurista društva" description="Id upitnika za 3. prokurista društva" display_to_user="true" display_group="2.4 Prokuristi društva" />
1330:     <data_field name="assignee_desc_is_pio" type="boolean" title="1. Zastupnik/punomoćenik društva je PIO" description="1. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1331:     <data_field name="assignee_desc_child_process_id" type="int" title="1. Id upitnika za zastupnika/punomoćenika društva" description="1. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1332:     <data_field name="assignee_desc_is_pio2" type="boolean" title="2. Zastupnik/punomoćenik društva je PIO" description="2. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1333:     <data_field name="assignee_desc_child_process_id2" type="int" title="2. Id upitnika za zastupnika/punomoćenika društva" description="2. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1334:     <data_field name="assignee_desc_is_pio3" type="boolean" title="3. Zastupnik/punomoćenik društva je PIO" description="3. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1335:     <data_field name="assignee_desc_child_process_id3" type="int" title="3. Id upitnika za zastupnika/punomoćenika društva" description="3. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1336:     <data_field name="assignee_desc_is_pio4" type="boolean" title="4. Zastupnik/punomoćenik društva je PIO" description="4. Zastupnik/punomoćenik društva je PIO" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
1337:     <data_field name="assignee_desc_child_process_id4" type="int" title="4. Id upitnika za zastupnika/punomoćenika društva" description="4. Id upitnika za zastupnika/punomoćenika društva" display_to_user="true" display_group="4. Zakonski zastupnik/punomoćenik" />
*/