select ID_GL_TIPI_RAC,* from dbo.gl_input_r


USE [NOVA_TEST]
GO

/****** Object:  Index [IX_GL_ARHIV_DD]    Script Date: 26.08.2021 11:48:12 ******/
CREATE NONCLUSTERED INDEX [IX_GL_ARHIV_DD] ON [dbo].[GL_ARHIV]
(
	[DATUM_DOK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

USE [NOVA_TEST]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_GL_ARHIV_IK]    Script Date: 26.08.2021 11:48:30 ******/
CREATE NONCLUSTERED INDEX [IX_GL_ARHIV_IK] ON [dbo].[GL_ARHIV]
(
	[ID_KUPCA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




USE [NOVA_TEST]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_GL_ARHIV_K_DD]    Script Date: 26.08.2021 11:48:42 ******/
CREATE NONCLUSTERED INDEX [IX_GL_ARHIV_K_DD] ON [dbo].[GL_ARHIV]
(
	[KONTO] ASC,
	[DATUM_DOK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO







sp_helptext grp_GL_Overview
sp_helptext gfn_GL_Overview2_Current
sp_helptext grp_GL_Razmej_View
sp_helptext gfn_Gl_Razmej_View