*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ˇˇATENCIÓN!! - ˇˇNO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="claims_mass_cancellation.scx" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*
*
#INCLUDE "..\..\common\includes\locs.h"

DEFINE CLASS dataenvironment AS dataenvironment 
 	*< CLASSDATA: Baseclass="dataenvironment" Timestamp="" Scale="" Uniqueid="" ClassIcon="2" />

	Name = "Dataenvironment"

ENDDEFINE

DEFINE CLASS frmclaim_mass_cancellation_pregled AS gform_pregled OF "..\..\common\classes\gkclass.vcx" 
 	*< CLASSDATA: Baseclass="form" Timestamp="" Scale="" Uniqueid="" />

	cursorname_detail = result
	DataSession = 2
	DoCreate = .T.
	Height = 500
	Name = "frmClaim_mass_cancellation_pregled"
	Width = 778
	bgridResult.Name = "bgridResult"
	cnt_Criteria.cmdRun.Name = "cmdRun"
	cnt_Criteria.Name = "cnt_Criteria"
	cnt_Criteria.shpBorder.Name = "shpBorder"
	cnt_Header.Name = "cnt_Header"
	cnt_Header.shpBorder.Name = "shpBorder"
	tbractions.btnAdditionalRoutines.Left = 455
	tbractions.btnAdditionalRoutines.Name = "btnAdditionalRoutines"
	tbractions.btnAdditionalRoutines.Top = 5
	tbractions.btnAverage.Left = 505
	tbractions.btnAverage.Name = "btnAverage"
	tbractions.btnAverage.Top = 5
	tbractions.btnBrisi.Enabled = .F.
	tbractions.btnBrisi.Left = 180
	tbractions.btnBrisi.Name = "btnBrisi"
	tbractions.btnBrisi.Top = 5
	tbractions.btnBrisi.Visible = .F.
	tbractions.btnDeselectAll.Left = 555
	tbractions.btnDeselectAll.Name = "btnDeselectAll"
	tbractions.btnDeselectAll.Top = 5
	tbractions.btnDodaj.Enabled = .F.
	tbractions.btnDodaj.Left = 105
	tbractions.btnDodaj.Name = "btnDodaj"
	tbractions.btnDodaj.Top = 5
	tbractions.btnDodaj.Visible = .F.
	tbractions.btnHelp.Left = 355
	tbractions.btnHelp.Name = "btnHelp"
	tbractions.btnHelp.Top = 5
	tbractions.btnIzhod.Left = 380
	tbractions.btnIzhod.Name = "btnIzhod"
	tbractions.btnIzhod.Top = 5
	tbractions.btnLegenda.Enabled = .F.
	tbractions.btnLegenda.Left = 705
	tbractions.btnLegenda.Name = "btnLegenda"
	tbractions.btnLegenda.Picture = ..\..\common\bmps\legenda.bmp
	tbractions.btnLegenda.Top = 5
	tbractions.btnLegenda.Visible = .F.
	tbractions.btnNaprej.Left = 55
	tbractions.btnNaprej.Name = "btnNaprej"
	tbractions.btnNaprej.Top = 5
	tbractions.btnNazaj.Left = 30
	tbractions.btnNazaj.Name = "btnNazaj"
	tbractions.btnNazaj.Top = 5
	tbractions.btnOdprteTabele.Left = 330
	tbractions.btnOdprteTabele.Name = "btnOdprteTabele"
	tbractions.btnOdprteTabele.Top = 5
	tbractions.btnPoprava.Enabled = .F.
	tbractions.btnPoprava.Left = 155
	tbractions.btnPoprava.Name = "btnPoprava"
	tbractions.btnPoprava.Top = 5
	tbractions.btnPoprava.Visible = .F.
	tbractions.btnPregled.Enabled = .F.
	tbractions.btnPregled.Left = 130
	tbractions.btnPregled.Name = "btnPregled"
	tbractions.btnPregled.Top = 5
	tbractions.btnPregled.Visible = .F.
	tbractions.btnPrvi.Left = 5
	tbractions.btnPrvi.Name = "btnPrvi"
	tbractions.btnPrvi.Top = 5
	tbractions.btnSelectAll.Left = 530
	tbractions.btnSelectAll.Name = "btnSelectAll"
	tbractions.btnSelectAll.Top = 5
	tbractions.btnSelekcija.Left = 230
	tbractions.btnSelekcija.Name = "btnSelekcija"
	tbractions.btnSelekcija.Top = 5
	tbractions.btnSelekcijaClear.Left = 430
	tbractions.btnSelekcijaClear.Name = "btnSelekcijaClear"
	tbractions.btnSelekcijaClear.Top = 5
	tbractions.btnShrani.Left = 205
	tbractions.btnShrani.Name = "btnShrani"
	tbractions.btnShrani.Top = 5
	tbractions.btnSortiranje.Left = 280
	tbractions.btnSortiranje.Name = "btnSortiranje"
	tbractions.btnSortiranje.Top = 5
	tbractions.btnTiskanje.Left = 255
	tbractions.btnTiskanje.Name = "btnTiskanje"
	tbractions.btnTiskanje.Top = 5
	tbractions.btnToolTip.Left = 405
	tbractions.btnToolTip.Name = "btnToolTip"
	tbractions.btnToolTip.Top = 5
	tbractions.btnTotal.Left = 305
	tbractions.btnTotal.Name = "btnTotal"
	tbractions.btnTotal.Top = 5
	tbractions.btnZadnji.Left = 80
	tbractions.btnZadnji.Name = "btnZadnji"
	tbractions.btnZadnji.Top = 5
	tbractions.ButtonCount = 30
	tbractions.cmdClear.Left = 630
	tbractions.cmdClear.Name = "cmdClear"
	tbractions.cmdClear.Top = 5
	tbractions.cmdOpenContract.Left = 680
	tbractions.cmdOpenContract.Name = "cmdOpenContract"
	tbractions.cmdOpenContract.Top = 5
	tbractions.cmdOpenCustomer.Left = 655
	tbractions.cmdOpenCustomer.Name = "cmdOpenCustomer"
	tbractions.cmdOpenCustomer.Top = 5
	tbractions.cmdRefresh.Left = 480
	tbractions.cmdRefresh.Name = "cmdRefresh"
	tbractions.cmdRefresh.Top = 5
	tbractions.cmdResize.Left = 580
	tbractions.cmdResize.Name = "cmdResize"
	tbractions.cmdResize.Top = 5
	tbractions.cmdRun.Left = 605
	tbractions.cmdRun.Name = "cmdRun"
	tbractions.cmdRun.Top = 5
	tbractions.Command30.Caption = ""
	tbractions.Command30.Height = 25
	tbractions.Command30.Left = 730
	tbractions.Command30.Name = "cmdStorno"
	tbractions.Command30.Picture = ..\..\common\bmps\checkon.bmp
	tbractions.Command30.SpecialEffect = 2
	tbractions.Command30.ToolTipText = "Storniraj izbrane terjatve"
	tbractions.Command30.Top = 5
	tbractions.Command30.Width = 25
	tbractions.Height = 34
	tbractions.Left = 0
	tbractions.Name = "tbractions"
	tbractions.Top = 0
	tbractions.Width = 768
	tmrClick.Name = "tmrClick"
	
	PROCEDURE set_permissions
		#INCLUDE ..\..\common\includes\locs.h
		
		LOCAL llIs_support
		llIs_support = GF_LOOKUP("users.is_support", GOBJ_Comm.UserData.GetUserName(), "users.username")
		
		IF !llIs_support THEN 
			pozor(STRTRAN(PERMISSION_DENIED, " '{0}'", ""))
			RETURN .F.
		ENDIF
	ENDPROC

	PROCEDURE tbractions.cmdStorno.Click
		LOCAL lcCursor_name, lcXml, lcAsk, ldDate, lcText
		lcCursor_name = thisform.cursorname_detail
		
		IF !USED(lcCursor_name) THEN
			RETURN .F.
		ENDIF
		
		SELECT &lcCursor_name
		LOCATE
		SELECT st_dok, id_cont, debit FROM &lcCursor_name WHERE oznacen = .T. INTO CURSOR st_dok_list
		
		IF RECCOUNT("st_dok_list") = 0 THEN
			pozor("Noben zapis ni označen!")
			RETURN .F.
		ENDIF
		
		lcAsk = "Ali želite stornirati označene terjatve?" &&caption
		IF !POTRJENO(lcAsk)
			RETURN .F.
		ENDIF
		
		lcTekst = "Masovna stornacija terjatev" &&caption
		tcDateName = "Datum SK" &&caption
		ldDate = DATE()
		DO FORM changedate_rpg WITH ldDate, lcTekst, "CNC", "", tcDateName TO loValues
		
		IF TYPE("loValues") # "O"
			RETURN .F.
		ENDIF
		
		lcXml = "<rpg_mass_claim_cancellation xmlns='urn:gmi:nova:leasing'>" + gcE
		
		SELECT st_dok_list
		GO TOP
		SCAN
			lcXml = lcXml + "<rpg_claim_cancellation_list>"
			lcXml = lcXml + GF_CreateNode("id_cont", st_dok_list.id_cont, "I", 1)
			lcXml = lcXml + GF_CreateNode("st_dok", st_dok_list.st_dok, "C", 1)
			lcXml = lcXml + GF_CreateNode("amount", st_dok_list.debit, "N", 1)
			lcXml = lcXml + "</rpg_claim_cancellation_list>"
		ENDSCAN
		USE IN st_dok_list
		
		lcXml = lcXml + GF_CreateNode("cancellation_date", loValues.datum, "D", 1)
		lcXml = lcXml + GF_CreateNode("rep_category", loValues.rpg_cat, "C", 1)
		lcXml = lcXml + GF_CreateNode("rpg_comment", loValues.opis, "C", 1)
		lcXml = lcXml + "</rpg_mass_claim_cancellation>"
		
		lcXmlResult = GF_ProcessXml(lcXml, .T., .T.)
		
		IF TYPE("lcXmlResult") = "C" THEN
			lcErrorDescr = GF_GetSingleNodeXml(lcXmlResult, "error_msg")
			IF GF_NULLOREMPTY(lcErrorDescr) THEN
				obvesti("Stornacija je uspešno zaključena.")
			ELSE
				LOCAL lcCaption
				lcCaption = "Naslednjih terjatev ni bilo mogoče stornirati"  && Caption
				pozor("Prišlo je do napake!")
				DO FORM message_memo WITH lcErrorDescr, lcCaption, .F.
			ENDIF
			thisform.runsql()
		ELSE
			pozor("Prišlo je do napake!")
			RETURN .F.
		ENDIF
	ENDPROC

ENDDEFINE
